import os
from code import InteractiveConsole
import urllib
import sublime
import sublime_plugin



class SymbolsListener(sublime_plugin.EventListener):

  # def on_activated(self, view):
  #   print("VLL: on_activated [%s]" % view)

  # def on_close(self, view):
  #   print("VLL: on_close [%s]" % view)

  # def on_deactivated(self, view):
  #   print("VLL: on_deactivated [%s]" % view)

  # def on_hover(self, view, pos, zone):
  #   zones = "T%s G%s M%s" %(sublime.HOVER_TEXT, sublime.HOVER_GUTTER, sublime.HOVER_MARGIN)
  #   print("VLL: on_hover [%s] [pos %s] [zone %s] %s" % (view, pos, zone, zones))

  # def on_load(self, view):
  #   print("VLL: on_load [%s]" % view)

  # def on_modified(self, view):
  #   print("VLL: on_modified [%s] [%s]" % (self,view))
  #   if hasattr(view, 'livePythonInterpreter'):
  #     print('VLL: Modified and interpreting.')
  #   else:
  #     print('VLL: Modified but not interpreting.')

  # def on_new(self, view):
  #   print("VLL: on_new [%s]" % view)

  # def on_post_save(self, view):
  #   print("VLL: on_post_save [%s]" % view)

  # def on_post_text_command(self, view, act, extras):
  #   act in ['move','drag_select','left_delete','right_delete','redo_or_repeat','find_next'] #....
  #   print("VLL: on_post_text_command [%s] [act %s] %s" % (view, act, extras))

  # def on_pre_close(self, view):
  #   print("VLL: on_pre_close [%s]" % view)

  # def on_pre_save(self, view):
  #   print("VLL: on_pre_save [%s]" % view)

  def on_query_completions(self, view, prefix, locations):
    # print("VLL: on_query_completions [%s] [%s] [%s]" % (view, prefix, locations))
    return [] or [
      ("prefix", "description", "prefix => value"),
      ("xcode",   "Code block", "```${1:syntax}\n${2:codes}\n```"),
      ("xmatlab", "Matlab code block", "```${1:matlab}\n${2:codes}\n```"),
      ("xpy",     "Python code block", "```${1:py}\n${2:codes}\n```"),
      ("xcpp",    "cpp code block", "```${1:cpp}\n${2:codes}\n```"),
      ("xcs",     "cs code block", "```${1:cs}\n${2:codes}\n```"),
      ("xxml",    "xml code block", "```${1:xml}\n${2:codes}\n```"),
      ("xjson",   "json code block", "```${1:json}\n${2:codes}\n```"),

      ("xCommonSymbol ℃", "Degree", "℃"),
      ("xCommonSymbol ©", "Copyright Symbol", "©"),
      ("xCommonSymbol ®", "Registered Sign", "®"),
      ("xCommonSymbol ™", "Trade Mark Sign", "™"),
      ("xCommonSymbol °", "Degree Symbol", "°"),
      ("xCommonSymbol ±", "Plus Minus Sign", "±"),
      ("xCommonSymbol ²", "Squared Symbol", "²"),
      ("xCommonSymbol ³", "Cubed Symbol", "³"),
      ("xCommonSymbol ¿", "Upside Down Question Mark", "¿"),
      ("xCommonSymbol €", "Euro Sign", "€"),
      ("xCommonSymbol £", "Pound Sign", "£"),
      ("xCommonSymbol ¥", "Yen Sign", "¥"),
      ("xCommonSymbol ₿", "Bitcoin Sign", "₿"),
      ("xCommonSymbol ¢", "Cent Sign", "¢"),
      ("xCommonSymbol ₱", "Peso Sign", "₱"),
      ("xCommonSymbol ⌀", "Diameter Sign", "⌀"),

      ("xsupA",    "Sub/Subscript", 'ᴬ'),
      ("xsupB",    "Sub/Subscript", 'ᴮ'),
      ("xsupC",    "Sub/Subscript", ''),
      ("xsupD",    "Sub/Subscript", 'ᴰ'),
      ("xsupE",    "Sub/Subscript", 'ᴱ'),
      ("xsupF",    "Sub/Subscript", '<sup>F</sup>'),
      ("xsupG",    "Sub/Subscript", 'ᴳ'),
      ("xsupH",    "Sub/Subscript", 'ᴴ'),
      ("xsupI",    "Sub/Subscript", 'ᴵ'),
      ("xsupJ",    "Sub/Subscript", 'ᴶ'),
      ("xsupK",    "Sub/Subscript", 'ᴷ'),
      ("xsupL",    "Sub/Subscript", 'ᴸ'),
      ("xsupM",    "Sub/Subscript", 'ᴹ'),
      ("xsupN",    "Sub/Subscript", 'ᴺ'),
      ("xsupO",    "Sub/Subscript", 'ᴼ'),
      ("xsupP",    "Sub/Subscript", 'ᴾ'),
      ("xsupQ",    "Sub/Subscript", '<sup>Q</sup>'),
      ("xsupR",    "Sub/Subscript", 'ᴿ'),
      ("xsupS",    "Sub/Subscript", '<sup>S</sup>'),
      ("xsupT",    "Sub/Subscript", 'ᵀ'),
      ("xsupU",    "Sub/Subscript", 'ᵁ'),
      ("xsupV",    "Sub/Subscript", 'ⱽ'),
      ("xsupW",    "Sub/Subscript", 'ᵂ'),
      ("xsupX",    "Sub/Subscript", '<sup>X</sup>'),
      ("xsupY",    "Sub/Subscript", '<sup>Y</sup>'),
      ("xsupZ",    "Sub/Subscript", '<sup>Z</sup>'),
 
      ("xsupa",    "Sub/Subscript", 'ᵃ'),
      ("xsupb",    "Sub/Subscript", 'ᵇ'),
      ("xsupc",    "Sub/Subscript", 'ᶜ'),
      ("xsupd",    "Sub/Subscript", 'ᵈ'),
      ("xsupe",    "Sub/Subscript", 'ᵉ'),
      ("xsupf",    "Sub/Subscript", 'ᶠ'),
      ("xsupg",    "Sub/Subscript", 'ᵍ'),
      ("xsuph",    "Sub/Subscript", 'ʰ'),
      ("xsupi",    "Sub/Subscript", 'ⁱ'),
      ("xsupj",    "Sub/Subscript", 'ʲ'),
      ("xsupk",    "Sub/Subscript", 'ᵏ'),
      ("xsupl",    "Sub/Subscript", 'ˡ'),
      ("xsupm",    "Sub/Subscript", 'ᵐ'),
      ("xsupn",    "Sub/Subscript", 'ⁿ'),
      ("xsupo",    "Sub/Subscript", 'ᵒ'),
      ("xsupp",    "Sub/Subscript", 'ᵖ'),
      ("xsupq",    "Sub/Subscript", '<sup>q</sup>'),
      ("xsupr",    "Sub/Subscript", 'ʳ'),
      ("xsups",    "Sub/Subscript", 'ˢ'),
      ("xsupt",    "Sub/Subscript", 'ᵗ'),
      ("xsupu",    "Sub/Subscript", 'ᵘ'),
      ("xsupv",    "Sub/Subscript", 'ᵛ'),
      ("xsupw",    "Sub/Subscript", 'ʷ'),
      ("xsupx",    "Sub/Subscript", 'ˣ'),
      ("xsupy",    "Sub/Subscript", 'ʸ'),
      ("xsupz",    "Sub/Subscript", 'ᶻ'),

      ("xArrows ←", "", "←"),
      ("xArrows →", "", "→"),
      ("xArrows ↑", "", "↑"),
      ("xArrows ↓", "", "↓"),
      ("xArrows ⟵", "", "⟵"),
      ("xArrows ⟶", "", "⟶"),
      ("xArrows ⇦", "", "⇦"),
      ("xArrows ⇨", "", "⇨"),
      ("xArrows ⇧", "", "⇧"),
      ("xArrows ⇩", "", "⇩"),
      ("xArrows ➡", "", "➡"),
      ("xArrows ⬅", "", "⬅"),
      ("xArrows ⮕", "", "⮕"),
      ("xArrows ⬆", "", "⬆"),
      ("xArrows ⬇", "", "⬇"),
      ("xArrows 🡐", "", "🡐"),
      ("xArrows 🡒", "", "🡒"),
      ("xArrows 🡑", "", "🡑"),
      ("xArrows 🡓", "", "🡓"),

      ("xDoubleSidedArrows ↔", "", "↔"),
      ("xDoubleSidedArrows ↕", "", "↕"),
      ("xDoubleSidedArrows ↚", "", "↚"),
      ("xDoubleSidedArrows ↛", "", "↛"),
      ("xDoubleSidedArrows ↮", "", "↮"),
      ("xDoubleSidedArrows ⟷", "", "⟷"),
      ("xDoubleSidedArrows ⬄", "", "⬄"),
      ("xDoubleSidedArrows ⇳", "", "⇳"),
      ("xDoubleSidedArrows ⬌", "", "⬌"),
      ("xDoubleSidedArrows ⬍", "", "⬍"),
      ("xDoubleSidedArrows 🡘", "", "🡘"),
      ("xDoubleSidedArrows 🡙", "", "🡙"),

      ("xDiagonalArrows ↖", "",  "↖"),
      ("xDiagonalArrows ↗", "",  "↗"),
      ("xDiagonalArrows ↘", "",  "↘"),
      ("xDiagonalArrows ↙", "",  "↙"),
      ("xDiagonalArrows ⤡", "",  "⤡"),
      ("xDiagonalArrows ⤢", "",  "⤢"),
      ("xDiagonalArrows ⬁", "",  "⬁"),
      ("xDiagonalArrows ⬀", "",  "⬀"),
      ("xDiagonalArrows ⬂", "",  "⬂"),
      ("xDiagonalArrows ⬃", "",  "⬃"),
      ("xDiagonalArrows ⬉", "",  "⬉"),
      ("xDiagonalArrows ⬈", "",  "⬈"),
      ("xDiagonalArrows ⬊", "",  "⬊"),
      ("xDiagonalArrows ⬋", "",  "⬋"),
      ("xDiagonalArrows 🡔", "",  "🡔"),
      ("xDiagonalArrows 🡕", "",  "🡕"),
      ("xDiagonalArrows 🡖", "",  "🡖"),
      ("xDiagonalArrows 🡗", "",  "🡗"),

      ("xPairedArrows ⮄", "", "⮄"),
      ("xPairedArrows ⮆", "", "⮆"),
      ("xPairedArrows ⮅", "", "⮅"),
      ("xPairedArrows ⮇", "", "⮇"),
      ("xPairedArrows ⇈", "", "⇈"),
      ("xPairedArrows ⇊", "", "⇊"),
      ("xPairedArrows ⇇", "", "⇇"),
      ("xPairedArrows ⇉", "", "⇉"),
      ("xPairedArrows ⇆", "", "⇆"),
      ("xPairedArrows ⇄", "", "⇄"),
      ("xPairedArrows ⇅", "", "⇅"),
      ("xPairedArrows ⇵", "", "⇵"),
      ("xPairedArrows ⮀", "", "⮀"),
      ("xPairedArrows ⮂", "", "⮂"),
      ("xPairedArrows ⮁", "", "⮁"),
      ("xPairedArrows ⮃", "", "⮃"),
      ("xPairedArrows ⭾", "", "⭾"),
      ("xPairedArrows ⭿", "", "⭿"),

      ("xSharpTurnArrows ⮠",  "",  "⮠"),
      ("xSharpTurnArrows ⮡",  "",  "⮡"),
      ("xSharpTurnArrows ⮢",  "",  "⮢"),
      ("xSharpTurnArrows ⮣",  "",  "⮣"),
      ("xSharpTurnArrows ⮤",  "",  "⮤"),
      ("xSharpTurnArrows ⮥",  "",  "⮥"),
      ("xSharpTurnArrows ⮦",  "",  "⮦"),
      ("xSharpTurnArrows ⮧",  "",  "⮧"),
      ("xSharpTurnArrows ↰",  "",  "↰"),
      ("xSharpTurnArrows ↱",  "",  "↱"),
      ("xSharpTurnArrows ↲",  "",  "↲"),
      ("xSharpTurnArrows ↳",  "",  "↳"),
      ("xSharpTurnArrows ⬐",  "",  "⬐"),
      ("xSharpTurnArrows ⬎",  "",  "⬎"),
      ("xSharpTurnArrows ⬑",  "",  "⬑"),
      ("xSharpTurnArrows ⬏",  "",  "⬏"),
      ("xSharpTurnArrows ↴",  "",  "↴"),
      ("xSharpTurnArrows ↵",  "",  "↵"),
      ("xSharpTurnArrows ⮐",  "",  "⮐"),
      ("xSharpTurnArrows ⮑",  "",  "⮑"),
      ("xSharpTurnArrows ⮒",  "",  "⮒"),
      ("xSharpTurnArrows ⮓",  "",  "⮓"),

      ("xArrowsHook ↩", "", "↩"),
      ("xArrowsHook ↪", "", "↪"),
      ("xArrowsHook ⤣", "", "⤣"),
      ("xArrowsHook ⤤", "", "⤤"),
      ("xArrowsHook ⤥", "", "⤥"),
      ("xArrowsHook ⤦", "", "⤦"),
      ("xArrowsHook ⭚", "", "⭚"),
      ("xArrowsHook ⭛", "", "⭛"),
      ("xArrowsHook ↫", "", "↫"),
      ("xArrowsHook ↬", "", "↬"),

      ("xsup0",    "Sub/Subscript", "⁰" ),
      ("xsup1",    "Sub/Subscript", "¹" ),
      ("xsup2",    "Sub/Subscript", "²" ),
      ("xsup3",    "Sub/Subscript", "³" ),
      ("xsup4",    "Sub/Subscript", "⁴" ),
      ("xsup5",    "Sub/Subscript", "⁵" ),
      ("xsup6",    "Sub/Subscript", "⁶" ),
      ("xsup7",    "Sub/Subscript", "⁷" ),
      ("xsup8",    "Sub/Subscript", "⁸" ),
      ("xsup9",    "Sub/Subscript", "⁹" ),
      ("xsup+",    "Sub/Subscript", "⁺" ),
      ("xsup-",    "Sub/Subscript", "⁻" ),
      ("xsup=",    "Sub/Subscript", "⁼" ),
      ("xsup(",    "Sub/Subscript", "⁽" ),
      ("xsup)",    "Sub/Subscript", "⁾" ),
      ("xsub0",    "Sub/Subscript", "₀" ),
      ("xsub1",    "Sub/Subscript", "₁" ),
      ("xsub2",    "Sub/Subscript", "₂" ),
      ("xsub3",    "Sub/Subscript", "₃" ),
      ("xsub4",    "Sub/Subscript", "₄" ),
      ("xsub5",    "Sub/Subscript", "₅" ),
      ("xsub6",    "Sub/Subscript", "₆" ),
      ("xsub7",    "Sub/Subscript", "₇" ),
      ("xsub8",    "Sub/Subscript", "₈" ),
      ("xsub9",    "Sub/Subscript", "₉" ),
      ("xsub+",    "Sub/Subscript", "₊" ),
      ("xsub-",    "Sub/Subscript", "₋" ),
      ("xsub=",    "Sub/Subscript", "₌" ),
      ("xsub(",    "Sub/Subscript", "₍" ),
      ("xsub)",    "Sub/Subscript", "₎" ),

      ("xMathSum ∑",  "Math Symbols", "∑" ),
      ("xMathSum ⨊", "Math Symbols", "⨊" ),
      ("xMathSum ⨁", "Math Symbols", "⨁" ),
      ("xMathProduct ⨀", "Math Symbols", "⨀" ),
      ("xMathProduct ⨂", "Math Symbols", "⨂" ),
      ("xMathProduct ∏", "Math Symbols", "∏" ),
      ("xMathProduct ∐", "Math Symbols", "∐" ),
      ("xMathProduct ⨉", "Math Symbols", "⨉" ),

      ("xGreek-U-a Α", "Greek Alphabet", "Α"),
      ("xGreek-U-b Β", "Greek Alphabet", "Β"),
      ("xGreek-U-c Γ", "Greek Alphabet", "Γ"),
      ("xGreek-U-d Δ", "Greek Alphabet", "Δ"),
      ("xGreek-U-e Ε", "Greek Alphabet", "Ε"),
      ("xGreek-U-f Ζ", "Greek Alphabet", "Ζ"),
      ("xGreek-U-g Η", "Greek Alphabet", "Η"),
      ("xGreek-U-h Θ", "Greek Alphabet", "Θ"),
      ("xGreek-U-i Ι", "Greek Alphabet", "Ι"),
      ("xGreek-U-j Κ", "Greek Alphabet", "Κ"),
      ("xGreek-U-k Λ", "Greek Alphabet", "Λ"),
      ("xGreek-U-l Μ", "Greek Alphabet", "Μ"),
      ("xGreek-U-m Ν", "Greek Alphabet", "Ν"),
      ("xGreek-U-n Ξ", "Greek Alphabet", "Ξ"),
      ("xGreek-U-o Ο", "Greek Alphabet", "Ο"),
      ("xGreek-U-p Π", "Greek Alphabet", "Π"),
      ("xGreek-U-q Ρ", "Greek Alphabet", "Ρ"),
      ("xGreek-U-r Σ", "Greek Alphabet", "Σ"),
      ("xGreek-U-s Τ", "Greek Alphabet", "Τ"),
      ("xGreek-U-t Υ", "Greek Alphabet", "Υ"),
      ("xGreek-U-u Φ", "Greek Alphabet", "Φ"),
      ("xGreek-U-v Χ", "Greek Alphabet", "Χ"),
      ("xGreek-U-w Ψ", "Greek Alphabet", "Ψ"),
      ("xGreek-U-x Ω", "Greek Alphabet", "Ω"),

      ("xGreek-L-a α", "Greek Alphabet", "α"),
      ("xGreek-L-b β", "Greek Alphabet", "β"),
      ("xGreek-L-c γ", "Greek Alphabet", "γ"),
      ("xGreek-L-d δ", "Greek Alphabet", "δ"),
      ("xGreek-L-e ε", "Greek Alphabet", "ε"),
      ("xGreek-L-f ζ", "Greek Alphabet", "ζ"),
      ("xGreek-L-g η", "Greek Alphabet", "η"),
      ("xGreek-L-h θ", "Greek Alphabet", "θ"),
      ("xGreek-L-i ι", "Greek Alphabet", "ι"),
      ("xGreek-L-j κ", "Greek Alphabet", "κ"),
      ("xGreek-L-k λ", "Greek Alphabet", "λ"),
      ("xGreek-L-l μ", "Greek Alphabet", "μ"),
      ("xGreek-L-m ν", "Greek Alphabet", "ν"),
      ("xGreek-L-n ξ", "Greek Alphabet", "ξ"),
      ("xGreek-L-o ο", "Greek Alphabet", "ο"),
      ("xGreek-L-p π", "Greek Alphabet", "π"),
      ("xGreek-L-q ρ", "Greek Alphabet", "ρ"),
      ("xGreek-L-r σ", "Greek Alphabet", "σ"),
      ("xGreek-L-s τ", "Greek Alphabet", "τ"),
      ("xGreek-L-t υ", "Greek Alphabet", "υ"),
      ("xGreek-L-u φ", "Greek Alphabet", "φ"),
      ("xGreek-L-v χ", "Greek Alphabet", "χ"),
      ("xGreek-L-w ψ", "Greek Alphabet", "ψ"),
      ("xGreek-L-x ω", "Greek Alphabet", "ω"),

      ("xGreek-U-Bold-a 𝚨", "Greek Alphabet", "𝚨"),
      ("xGreek-U-Bold-b 𝚩", "Greek Alphabet", "𝚩"),
      ("xGreek-U-Bold-c 𝚪", "Greek Alphabet", "𝚪"),
      ("xGreek-U-Bold-d 𝚫", "Greek Alphabet", "𝚫"),
      ("xGreek-U-Bold-e 𝚬", "Greek Alphabet", "𝚬"),
      ("xGreek-U-Bold-f 𝚭", "Greek Alphabet", "𝚭"),
      ("xGreek-U-Bold-g 𝚮", "Greek Alphabet", "𝚮"),
      ("xGreek-U-Bold-h 𝚯", "Greek Alphabet", "𝚯"),
      ("xGreek-U-Bold-i 𝚰", "Greek Alphabet", "𝚰"),
      ("xGreek-U-Bold-j 𝚱", "Greek Alphabet", "𝚱"),
      ("xGreek-U-Bold-k 𝚲", "Greek Alphabet", "𝚲"),
      ("xGreek-U-Bold-l 𝚳", "Greek Alphabet", "𝚳"),
      ("xGreek-U-Bold-m 𝚴", "Greek Alphabet", "𝚴"),
      ("xGreek-U-Bold-n 𝚵", "Greek Alphabet", "𝚵"),
      ("xGreek-U-Bold-o 𝚶", "Greek Alphabet", "𝚶"),
      ("xGreek-U-Bold-p 𝚷", "Greek Alphabet", "𝚷"),
      ("xGreek-U-Bold-q 𝚸", "Greek Alphabet", "𝚸"),
      ("xGreek-U-Bold-r 𝚺", "Greek Alphabet", "𝚺"),
      ("xGreek-U-Bold-s 𝚻", "Greek Alphabet", "𝚻"),
      ("xGreek-U-Bold-t 𝚼", "Greek Alphabet", "𝚼"),
      ("xGreek-U-Bold-u 𝚽", "Greek Alphabet", "𝚽"),
      ("xGreek-U-Bold-v 𝚾", "Greek Alphabet", "𝚾"),
      ("xGreek-U-Bold-w 𝚿", "Greek Alphabet", "𝚿"),
      ("xGreek-U-Bold-x 𝛀", "Greek Alphabet", "𝛀"),

      ("xGreek-L-Bold-a 𝛂", "Greek Alphabet", "𝛂"),
      ("xGreek-L-Bold-b 𝛃", "Greek Alphabet", "𝛃"),
      ("xGreek-L-Bold-c 𝛄", "Greek Alphabet", "𝛄"),
      ("xGreek-L-Bold-d 𝛅", "Greek Alphabet", "𝛅"),
      ("xGreek-L-Bold-e 𝛆", "Greek Alphabet", "𝛆"),
      ("xGreek-L-Bold-f 𝛇", "Greek Alphabet", "𝛇"),
      ("xGreek-L-Bold-g 𝛈", "Greek Alphabet", "𝛈"),
      ("xGreek-L-Bold-h 𝛉", "Greek Alphabet", "𝛉"),
      ("xGreek-L-Bold-i 𝛊", "Greek Alphabet", "𝛊"),
      ("xGreek-L-Bold-j 𝛋", "Greek Alphabet", "𝛋"),
      ("xGreek-L-Bold-k 𝛌", "Greek Alphabet", "𝛌"),
      ("xGreek-L-Bold-l 𝛍", "Greek Alphabet", "𝛍"),
      ("xGreek-L-Bold-m 𝛎", "Greek Alphabet", "𝛎"),
      ("xGreek-L-Bold-n 𝛏", "Greek Alphabet", "𝛏"),
      ("xGreek-L-Bold-o 𝛐", "Greek Alphabet", "𝛐"),
      ("xGreek-L-Bold-p 𝛑", "Greek Alphabet", "𝛑"),
      ("xGreek-L-Bold-q 𝛒", "Greek Alphabet", "𝛒"),
      ("xGreek-L-Bold-r 𝛔", "Greek Alphabet", "𝛔"),
      ("xGreek-L-Bold-s 𝛕", "Greek Alphabet", "𝛕"),
      ("xGreek-L-Bold-t 𝛖", "Greek Alphabet", "𝛖"),
      ("xGreek-L-Bold-u 𝛗", "Greek Alphabet", "𝛗"),
      ("xGreek-L-Bold-v 𝛘", "Greek Alphabet", "𝛘"),
      ("xGreek-L-Bold-w 𝛙", "Greek Alphabet", "𝛙"),
      ("xGreek-L-Bold-x 𝛚", "Greek Alphabet", "𝛚"),

      ("xGreek-U-Italic-a 𝛢", "Greek Alphabet", "𝛢"),
      ("xGreek-U-Italic-b 𝛣", "Greek Alphabet", "𝛣"),
      ("xGreek-U-Italic-c 𝛤", "Greek Alphabet", "𝛤"),
      ("xGreek-U-Italic-d 𝛥", "Greek Alphabet", "𝛥"),
      ("xGreek-U-Italic-e 𝛦", "Greek Alphabet", "𝛦"),
      ("xGreek-U-Italic-f 𝛧", "Greek Alphabet", "𝛧"),
      ("xGreek-U-Italic-g 𝛨", "Greek Alphabet", "𝛨"),
      ("xGreek-U-Italic-h 𝛩", "Greek Alphabet", "𝛩"),
      ("xGreek-U-Italic-i 𝛪", "Greek Alphabet", "𝛪"),
      ("xGreek-U-Italic-j 𝛫", "Greek Alphabet", "𝛫"),
      ("xGreek-U-Italic-k 𝛬", "Greek Alphabet", "𝛬"),
      ("xGreek-U-Italic-l 𝛭", "Greek Alphabet", "𝛭"),
      ("xGreek-U-Italic-m 𝛮", "Greek Alphabet", "𝛮"),
      ("xGreek-U-Italic-n 𝛯", "Greek Alphabet", "𝛯"),
      ("xGreek-U-Italic-o 𝛰", "Greek Alphabet", "𝛰"),
      ("xGreek-U-Italic-p 𝛱", "Greek Alphabet", "𝛱"),
      ("xGreek-U-Italic-q 𝛲", "Greek Alphabet", "𝛲"),
      ("xGreek-U-Italic-r 𝛴", "Greek Alphabet", "𝛴"),
      ("xGreek-U-Italic-s 𝛵", "Greek Alphabet", "𝛵"),
      ("xGreek-U-Italic-t 𝛶", "Greek Alphabet", "𝛶"),
      ("xGreek-U-Italic-u 𝛷", "Greek Alphabet", "𝛷"),
      ("xGreek-U-Italic-v 𝛸", "Greek Alphabet", "𝛸"),
      ("xGreek-U-Italic-w 𝛹", "Greek Alphabet", "𝛹"),
      ("xGreek-U-Italic-x 𝛺", "Greek Alphabet", "𝛺"),

      ("xGreek-L-Italic-a 𝛼", "Greek Alphabet", "𝛼"),
      ("xGreek-L-Italic-b 𝛽", "Greek Alphabet", "𝛽"),
      ("xGreek-L-Italic-c 𝛾", "Greek Alphabet", "𝛾"),
      ("xGreek-L-Italic-d 𝛿", "Greek Alphabet", "𝛿"),
      ("xGreek-L-Italic-e 𝜀", "Greek Alphabet", "𝜀"),
      ("xGreek-L-Italic-f 𝜁", "Greek Alphabet", "𝜁"),
      ("xGreek-L-Italic-g 𝜂", "Greek Alphabet", "𝜂"),
      ("xGreek-L-Italic-h 𝜃", "Greek Alphabet", "𝜃"),
      ("xGreek-L-Italic-i 𝜄", "Greek Alphabet", "𝜄"),
      ("xGreek-L-Italic-j 𝜅", "Greek Alphabet", "𝜅"),
      ("xGreek-L-Italic-k 𝜆", "Greek Alphabet", "𝜆"),
      ("xGreek-L-Italic-l 𝜇", "Greek Alphabet", "𝜇"),
      ("xGreek-L-Italic-m 𝜈", "Greek Alphabet", "𝜈"),
      ("xGreek-L-Italic-n 𝜉", "Greek Alphabet", "𝜉"),
      ("xGreek-L-Italic-o 𝜊", "Greek Alphabet", "𝜊"),
      ("xGreek-L-Italic-p 𝜋", "Greek Alphabet", "𝜋"),
      ("xGreek-L-Italic-q 𝜌", "Greek Alphabet", "𝜌"),
      ("xGreek-L-Italic-r 𝜎", "Greek Alphabet", "𝜎"),
      ("xGreek-L-Italic-s 𝜏", "Greek Alphabet", "𝜏"),
      ("xGreek-L-Italic-t 𝜐", "Greek Alphabet", "𝜐"),
      ("xGreek-L-Italic-u 𝜑", "Greek Alphabet", "𝜑"),
      ("xGreek-L-Italic-v 𝜒", "Greek Alphabet", "𝜒"),
      ("xGreek-L-Italic-w 𝜓", "Greek Alphabet", "𝜓"),
      ("xGreek-L-Italic-x 𝜔", "Greek Alphabet", "𝜔"),
 
      ("xDoubleStruck-A 𝔸", "Double-struck", "𝔸"),
      ("xDoubleStruck-B 𝔹", "Double-struck", "𝔹"),
      ("xDoubleStruck-C ℂ", "Double-struck", "ℂ"),
      ("xDoubleStruck-D 𝔻", "Double-struck", "𝔻"),
      ("xDoubleStruck-E 𝔼", "Double-struck", "𝔼"),
      ("xDoubleStruck-F 𝔽", "Double-struck", "𝔽"),
      ("xDoubleStruck-G 𝔾", "Double-struck", "𝔾"),
      ("xDoubleStruck-H ℍ", "Double-struck", "ℍ"),
      ("xDoubleStruck-I 𝕀", "Double-struck", "𝕀"),
      ("xDoubleStruck-J 𝕁", "Double-struck", "𝕁"),
      ("xDoubleStruck-K 𝕂", "Double-struck", "𝕂"),
      ("xDoubleStruck-L 𝕃", "Double-struck", "𝕃"),
      ("xDoubleStruck-M 𝕄", "Double-struck", "𝕄"),
      ("xDoubleStruck-N ℕ", "Double-struck", "ℕ"),
      ("xDoubleStruck-O 𝕆", "Double-struck", "𝕆"),
      ("xDoubleStruck-P ℙ", "Double-struck", "ℙ"),
      ("xDoubleStruck-Q ℚ", "Double-struck", "ℚ"),
      ("xDoubleStruck-R ℝ", "Double-struck", "ℝ"),
      ("xDoubleStruck-S 𝕊", "Double-struck", "𝕊"),
      ("xDoubleStruck-T 𝕋", "Double-struck", "𝕋"),
      ("xDoubleStruck-U 𝕌", "Double-struck", "𝕌"),
      ("xDoubleStruck-V 𝕍", "Double-struck", "𝕍"),
      ("xDoubleStruck-W 𝕎", "Double-struck", "𝕎"),
      ("xDoubleStruck-X 𝕏", "Double-struck", "𝕏"),
      ("xDoubleStruck-Y 𝕐", "Double-struck", "𝕐"),
      ("xDoubleStruck-Z ℤ", "Double-struck", "ℤ"),
 
      ("xDoubleStruck-a 𝕒", "Double-struck", "𝕒"),
      ("xDoubleStruck-b 𝕓", "Double-struck", "𝕓"),
      ("xDoubleStruck-c 𝕔", "Double-struck", "𝕔"),
      ("xDoubleStruck-d 𝕕", "Double-struck", "𝕕"),
      ("xDoubleStruck-e 𝕖", "Double-struck", "𝕖"),
      ("xDoubleStruck-f 𝕗", "Double-struck", "𝕗"),
      ("xDoubleStruck-g 𝕘", "Double-struck", "𝕘"),
      ("xDoubleStruck-h 𝕙", "Double-struck", "𝕙"),
      ("xDoubleStruck-i 𝕚", "Double-struck", "𝕚"),
      ("xDoubleStruck-j 𝕛", "Double-struck", "𝕛"),
      ("xDoubleStruck-k 𝕜", "Double-struck", "𝕜"),
      ("xDoubleStruck-l 𝕝", "Double-struck", "𝕝"),
      ("xDoubleStruck-m 𝕞", "Double-struck", "𝕞"),
      ("xDoubleStruck-n 𝕟", "Double-struck", "𝕟"),
      ("xDoubleStruck-o 𝕠", "Double-struck", "𝕠"),
      ("xDoubleStruck-p 𝕡", "Double-struck", "𝕡"),
      ("xDoubleStruck-q 𝕢", "Double-struck", "𝕢"),
      ("xDoubleStruck-r 𝕣", "Double-struck", "𝕣"),
      ("xDoubleStruck-s 𝕤", "Double-struck", "𝕤"),
      ("xDoubleStruck-t 𝕥", "Double-struck", "𝕥"),
      ("xDoubleStruck-u 𝕦", "Double-struck", "𝕦"),
      ("xDoubleStruck-v 𝕧", "Double-struck", "𝕧"),
      ("xDoubleStruck-w 𝕨", "Double-struck", "𝕨"),
      ("xDoubleStruck-x 𝕩", "Double-struck", "𝕩"),
      ("xDoubleStruck-y 𝕪", "Double-struck", "𝕪"),
      ("xDoubleStruck-z 𝕫", "Double-struck", "𝕫"),
 
      ("xDoubleStruck-0 𝟘", "Double-struck", "𝟘"),
      ("xDoubleStruck-1 𝟙", "Double-struck", "𝟙"),
      ("xDoubleStruck-2 𝟚", "Double-struck", "𝟚"),
      ("xDoubleStruck-3 𝟛", "Double-struck", "𝟛"),
      ("xDoubleStruck-4 𝟜", "Double-struck", "𝟜"),
      ("xDoubleStruck-5 𝟝", "Double-struck", "𝟝"),
      ("xDoubleStruck-6 𝟞", "Double-struck", "𝟞"),
      ("xDoubleStruck-7 𝟟", "Double-struck", "𝟟"),
      ("xDoubleStruck-8 𝟠", "Double-struck", "𝟠"),
      ("xDoubleStruck-9 𝟡", "Double-struck", "𝟡"),
      ]

  # def on_query_context(self, view, key, op, opr, match_all):
  #   print("VLL: on_query_context [%s] [%s] [%s] [%s] [%s]" % (view, key, op, opr, match_all))       

  # def on_selection_modified(self, view):
  #   print("VLL: on_selection_modified [%s]" % view)

  # def on_text_command(self, view, act, extras):
  #   act in ['move','drag_select','left_delete','right_delete','redo_or_repeat','find_next'] #....
  #   print("VLL: on_text_command [%s] [act %s] %s" % (view, act, extras))

  # def on_window_command(self, view, act, b):
  #   act in ['new_file', 'close']
  #   print("VLL: on_window_command [%s] [act %s] [%s]" % (view, act, b))

