import os
from code import InteractiveConsole
import urllib
import sublime
import sublime_plugin


class SymbolsListener(sublime_plugin.EventListener):

    # def on_activated(self, view):
    #   print("VLL: on_activated [%s]" % view)

    # def on_close(self, view):
    #   print("VLL: on_close [%s]" % view)

    # def on_deactivated(self, view):
    #   print("VLL: on_deactivated [%s]" % view)

    # def on_hover(self, view, pos, zone):
    #   zones = "T%s G%s M%s" %(sublime.HOVER_TEXT, sublime.HOVER_GUTTER, sublime.HOVER_MARGIN)
    #   print("VLL: on_hover [%s] [pos %s] [zone %s] %s" % (view, pos, zone, zones))

    # def on_load(self, view):
    #   print("VLL: on_load [%s]" % view)

    # def on_modified(self, view):
    #   print("VLL: on_modified [%s] [%s]" % (self,view))
    #   if hasattr(view, 'livePythonInterpreter'):
    #     print('VLL: Modified and interpreting.')
    #   else:
    #     print('VLL: Modified but not interpreting.')

    # def on_new(self, view):
    #   print("VLL: on_new [%s]" % view)

    # def on_post_save(self, view):
    #   print("VLL: on_post_save [%s]" % view)

    # def on_post_text_command(self, view, act, extras):
    #   act in ['move','drag_select','left_delete','right_delete','redo_or_repeat','find_next'] #....
    #   print("VLL: on_post_text_command [%s] [act %s] %s" % (view, act, extras))

    # def on_pre_close(self, view):
    #   print("VLL: on_pre_close [%s]" % view)

    # def on_pre_save(self, view):
    #   print("VLL: on_pre_save [%s]" % view)

    def on_query_completions(self, view, prefix, locations):
        # print("VLL: on_query_completions [%s] [%s] [%s]" % (view, prefix, locations))
        rgn = view.sel()[0]
        scope = view.scope_name(rgn.a)
        # print("⚠scope_name", scope)
        if scope.find("string.quoted") == -1 and scope.find("source.") != -1:
            return
        return [] or [
            ("prefix", "description", "prefix => value"),
            ("xcode",   "Code block", "```${1:syntax}\n${2:codes}\n```"),
            ("xmatlab", "Matlab code block", "```${1:matlab}\n${2:codes}\n```"),
            ("xpy",     "Python code block", "```${1:py}\n${2:codes}\n```"),
            ("xcpp",    "cpp code block", "```${1:cpp}\n${2:codes}\n```"),
            ("xbash",    "sh code block", "```${1:sh}\n${2:codes}\n```"),
            ("xcs",     "cs code block", "```${1:cs}\n${2:codes}\n```"),
            ("xxml",    "xml code block", "```${1:xml}\n${2:codes}\n```"),
            ("xjson",   "json code block", "```${1:json}\n${2:codes}\n```"),

            ("xhelp",   "x code help block", "```yaml\n\
xCommonSymbol:                \n\
                        →  Degree 37℃,   \n\
xsupA:                        \n\
                        → Sub/Subscript Aᴬn\
xsupa:                        \n\
                        → Sub/Subscript aᵃn\
xArrows:                      \n\
                        →  ←              \n\
xDoubleArrows:                \n\
                        →  ↔              \n\
xDiagonalArrows:              \n\
                        →  ↖              \n\
xPairedArrows:                \n\
                        →  ⮄             \n\
xSharpTurnArrows:             \n\
                        →  ⮠              \n\
xArrowsHook:                  \n\
                        →  ↩             \n\
xsup0:                        \n\
                        → Sub/Subscript x²\n\
xMathSum:                     \n\
                        → Math Symbols ∑  \n\
xGreek-U-a:                   \n\
                        → Greek Alphabet Α \n\
xGreek-L-a:                   \n\
                        → Greek Alphabet α\n\
xGreek-BU-a:              \n\
                        → Greek Alphabet 𝚨\n\
xGreek-BL-a:              \n\
                        → Greek Alphabet 𝛂\n\
xGreek-IU-a:            \n\
                        → Greek Alphabet 𝛢\n\
xGreek-IL-a:            \n\
                        → Greek Alphabet 𝛼\n\
xDoubleStruck-A:              \n\
                        → Double-struck 𝔸\n\
xDoubleStruck-a:              \n\
                        → Double-struck 𝕒 \n\
xDoubleStruck-0:              \n\
                        → Double-struck 𝟘 \n\
```"),

            ("xCommonSymbol ℃", "Degree", "℃"),
            ("xCommonSymbol ©", "Copyright Symbol", "©"),
            ("xCommonSymbol ®", "Registered Sign", "®"),
            ("xCommonSymbol ™", "Trade Mark Sign", "™"),
            ("xCommonSymbol °", "Degree Symbol", "°"),
            ("xCommonSymbol ±", "Plus Minus Sign", "±"),
            ("xCommonSymbol ²", "Squared Symbol", "²"),
            ("xCommonSymbol ³", "Cubed Symbol", "³"),
            ("xCommonSymbol ¿", "Upside Down Question Mark", "¿"),
            ("xCommonSymbol €", "Euro Sign", "€"),
            ("xCommonSymbol £", "Pound Sign", "£"),
            ("xCommonSymbol ¥", "Yen Sign", "¥"),
            ("xCommonSymbol ₿", "Bitcoin Sign", "₿"),
            ("xCommonSymbol ¢", "Cent Sign", "¢"),
            ("xCommonSymbol ₱", "Peso Sign", "₱"),
            ("xCommonSymbol ⌀", "Diameter Sign", "⌀"),

            ("xSection §", "", "§"),

            ("xsupA",    "Sub/Subscript", 'ᴬ'),
            ("xsupB",    "Sub/Subscript", 'ᴮ'),
            ("xsupC",    "Sub/Subscript", ''),
            ("xsupD",    "Sub/Subscript", 'ᴰ'),
            ("xsupE",    "Sub/Subscript", 'ᴱ'),
            ("xsupF",    "Sub/Subscript", '<sup>F</sup>'),
            ("xsupG",    "Sub/Subscript", 'ᴳ'),
            ("xsupH",    "Sub/Subscript", 'ᴴ'),
            ("xsupI",    "Sub/Subscript", 'ᴵ'),
            ("xsupJ",    "Sub/Subscript", 'ᴶ'),
            ("xsupK",    "Sub/Subscript", 'ᴷ'),
            ("xsupL",    "Sub/Subscript", 'ᴸ'),
            ("xsupM",    "Sub/Subscript", 'ᴹ'),
            ("xsupN",    "Sub/Subscript", 'ᴺ'),
            ("xsupO",    "Sub/Subscript", 'ᴼ'),
            ("xsupP",    "Sub/Subscript", 'ᴾ'),
            ("xsupQ",    "Sub/Subscript", '<sup>Q</sup>'),
            ("xsupR",    "Sub/Subscript", 'ᴿ'),
            ("xsupS",    "Sub/Subscript", '<sup>S</sup>'),
            ("xsupT",    "Sub/Subscript", 'ᵀ'),
            ("xsupU",    "Sub/Subscript", 'ᵁ'),
            ("xsupV",    "Sub/Subscript", 'ⱽ'),
            ("xsupW",    "Sub/Subscript", 'ᵂ'),
            ("xsupX",    "Sub/Subscript", '<sup>X</sup>'),
            ("xsupY",    "Sub/Subscript", '<sup>Y</sup>'),
            ("xsupZ",    "Sub/Subscript", '<sup>Z</sup>'),

            ("xsupa",    "Sub/Subscript", 'ᵃ'),
            ("xsupb",    "Sub/Subscript", 'ᵇ'),
            ("xsupc",    "Sub/Subscript", 'ᶜ'),
            ("xsupd",    "Sub/Subscript", 'ᵈ'),
            ("xsupe",    "Sub/Subscript", 'ᵉ'),
            ("xsupf",    "Sub/Subscript", 'ᶠ'),
            ("xsupg",    "Sub/Subscript", 'ᵍ'),
            ("xsuph",    "Sub/Subscript", 'ʰ'),
            ("xsupi",    "Sub/Subscript", 'ⁱ'),
            ("xsupj",    "Sub/Subscript", 'ʲ'),
            ("xsupk",    "Sub/Subscript", 'ᵏ'),
            ("xsupl",    "Sub/Subscript", 'ˡ'),
            ("xsupm",    "Sub/Subscript", 'ᵐ'),
            ("xsupn",    "Sub/Subscript", 'ⁿ'),
            ("xsupo",    "Sub/Subscript", 'ᵒ'),
            ("xsupp",    "Sub/Subscript", 'ᵖ'),
            ("xsupq",    "Sub/Subscript", '<sup>q</sup>'),
            ("xsupr",    "Sub/Subscript", 'ʳ'),
            ("xsups",    "Sub/Subscript", 'ˢ'),
            ("xsupt",    "Sub/Subscript", 'ᵗ'),
            ("xsupu",    "Sub/Subscript", 'ᵘ'),
            ("xsupv",    "Sub/Subscript", 'ᵛ'),
            ("xsupw",    "Sub/Subscript", 'ʷ'),
            ("xsupx",    "Sub/Subscript", 'ˣ'),
            ("xsupy",    "Sub/Subscript", 'ʸ'),
            ("xsupz",    "Sub/Subscript", 'ᶻ'),

            ("xsubₐ",    "Sub/Subscript", 'ₐ'),
            ("xsubₑ",    "Sub/Subscript", 'ₑ'),
            ("xsubₕ",    "Sub/Subscript", 'ₕ'),
            ("xsubᵢ",    "Sub/Subscript", 'ᵢ'),
            ("xsubⱼ",    "Sub/Subscript", 'ⱼ'),
            ("xsubₗ",    "Sub/Subscript", 'ₗ'),
            ("xsubₘ",    "Sub/Subscript", 'ₘ'),
            ("xsubₙ",    "Sub/Subscript", 'ₙ'),
            ("xsubₒ",    "Sub/Subscript", 'ₒ'),
            ("xsubₚ",    "Sub/Subscript", 'ₚ'),
            ("xsubᵣ",    "Sub/Subscript", 'ᵣ'),
            ("xsubₛ",    "Sub/Subscript", 'ₛ'),
            ("xsubₜ",    "Sub/Subscript", 'ₜ'),
            ("xsubᵤ",    "Sub/Subscript", 'ᵤ'),
            ("xsubᵥ",    "Sub/Subscript", 'ᵥ'),
            ("xsubₓ",    "Sub/Subscript", 'ₓ'),
            
            ("xArrowsA-L ←", "", "←"),
            ("xArrowsA-R →", "", "→"),
            ("xArrowsA-U ↑", "", "↑"),
            ("xArrowsA-D ↓", "", "↓"),
            ("xArrowsB-L ⇦", "", "⇦"),
            ("xArrowsB-R ⇨", "", "⇨"),
            ("xArrowsB-U ⇧", "", "⇧"),
            ("xArrowsB-D ⇩", "", "⇩"),
            ("xArrowsC-L ⬅", "", "⬅"),
            ("xArrowsC-R ➡", "", "➡"),
            ("xArrowsC-U ⬆", "", "⬆"),
            ("xArrowsC-D ⬇", "", "⬇"),
            ("xArrowsD-L 🡐", "", "🡐"),
            ("xArrowsD-R 🡒", "", "🡒"),
            ("xArrowsD-U 🡑", "", "🡑"),
            ("xArrowsD-D 🡓", "", "🡓"),
            ("xArrowsE-L ⟵", "", "⟵"),
            ("xArrowsE-R ⟶", "", "⟶"),
            ("xArrowsF-R ⮕", "", "⮕"),

            ("xBentArrows-U ⭜", "", "⭜"),
            ("xBentArrows-D ⭝", "", "⭝"),
            ("xBentArrows-R ⭞", "", "⭞"),
            ("xBentArrows-R ⭟", "", "⭟"),
            ("xBentArrows-D ↯", "", "↯"),
            ("xBentArrows-LD ⭍", "", "⭍"),

            ( "xMathArrowsA-R ⤼",  " ",  "⤼"),
            ( "xMathArrowsA-L ⤽",  " ",  "⤽"),
            ( "xMathArrowsB-L ⥶",  " ",  "⥶"),
            ( "xMathArrowsB-R ⥸",  " ",  "⥸"),
            ( "xMathArrowsC-L ⥷",  " ",  "⥷"),
            ( "xMathArrowsC-R ⭃",  " ",  "⭃"),
            ( "xMathArrowsD-L ⭀",  " ",  "⭀"),
            ( "xMathArrowsD-R ⥱",  " ",  "⥱"),
            ( "xMathArrowsE-L ⭂",  " ",  "⭂"),
            ( "xMathArrowsE-R ⭈",  " ",  "⭈"),
            ( "xMathArrowsE-L ⭊",  " ",  "⭊"),
            ( "xMathArrowsE-R ⥵",  " ",  "⥵"),
            ( "xMathArrowsF-L ⭁",  " ",  "⭁"),
            ( "xMathArrowsF-R ⭇",  " ",  "⭇"),
            ( "xMathArrowsF-L ⭉",  " ",  "⭉"),
            ( "xMathArrowsF-R ⥲",  " ",  "⥲"),
            ( "xMathArrowsG-L ⭋",  " ",  "⭋"),
            ( "xMathArrowsG-R ⭌",  " ",  "⭌"),
            ( "xMathArrowsG-L ⥳",  " ",  "⥳"),
            ( "xMathArrowsG-R ⥴",  " ",  "⥴"),
            ( "xMathArrowsG-L ⥆",  " ",  "⥆"),
            ( "xMathArrowsG-R ⥅",  " ",  "⥅"),
            ( "xMathArrowsH-L ⬰",  " ",  "⬰"),
            ( "xMathArrowsH-R ⇴",  " ",  "⇴"),
            ( "xMathArrowsH-LR ⥈",  " ",  "⥈"),
            ( "xMathArrowsH-L ⬲",  " ",  "⬲"),
            ( "xMathArrowsH-R ⟴",  " ",  "⟴"),
            ( "xMathArrowsI-L ⬾",  " ",  "⬾"),
            ( "xMathArrowsI-R ⥇",  " ",  "⥇"),
            ( "xMathArrowsJ-R ⥹",  " ",  "⥹"),
            ( "xMathArrowsJ-L ⥻",  " ",  "⥻"),
            ( "xMathArrowsJ-L ⥺",  " ",  "⥺"),
            ( "xMathArrowsJ-R ⭄",  " ",  "⭄"),

            ("xDoubleArrowsA-LR ↔", "", "↔"),
            ("xDoubleArrowsA-UD ↕", "", "↕"),
            ("xDoubleArrowsB-L ↚", "", "↚"),
            ("xDoubleArrowsB-R ↛", "", "↛"),
            ("xDoubleArrowsB-R ↮", "", "↮"),
            ("xDoubleArrowsE-LR ⟷", "", "⟷"),
            ("xDoubleArrowsC-LR ⬄", "", "⬄"),
            ("xDoubleArrowsC-UD ⇳", "", "⇳"),
            ("xDoubleArrowsD-UD ⬌", "", "⬌"),
            ("xDoubleArrowsD-UD ⬍", "", "⬍"),
            ("xDoubleArrowsF-LR 🡘", "", "🡘"),
            ("xDoubleArrowsF-UD 🡙", "", "🡙"),

            ("xDiagonalArrowsA-LU ↖", "",  "↖"),
            ("xDiagonalArrowsA-RU ↗", "",  "↗"),
            ("xDiagonalArrowsA-RD ↘", "",  "↘"),
            ("xDiagonalArrowsA-LD ↙", "",  "↙"),
            ("xDiagonalArrowsB-LU ⬁", "",  "⬁"),
            ("xDiagonalArrowsB-RU ⬀", "",  "⬀"),
            ("xDiagonalArrowsB-RD ⬂", "",  "⬂"),
            ("xDiagonalArrowsB-LD ⬃", "",  "⬃"),
            ("xDiagonalArrowsC-LU ⬉", "",  "⬉"),
            ("xDiagonalArrowsC-RU ⬈", "",  "⬈"),
            ("xDiagonalArrowsC-RD ⬊", "",  "⬊"),
            ("xDiagonalArrowsC-LD ⬋", "",  "⬋"),
            ("xDiagonalArrowsD-LU 🡔", "",  "🡔"),
            ("xDiagonalArrowsD-RU 🡕", "",  "🡕"),
            ("xDiagonalArrowsD-RD 🡖", "",  "🡖"),
            ("xDiagonalArrowsD-LD 🡗", "",  "🡗"),
            ("xDiagonalArrowsE-LURD ⤡", "",  "⤡"),
            ("xDiagonalArrowsE-LDRU ⤢", "",  "⤢"),

            ("xPairedArrowsA-LL ⮄", "", "⮄"),
            ("xPairedArrowsA-RR ⮆", "", "⮆"),
            ("xPairedArrowsA-UU ⮅", "", "⮅"),
            ("xPairedArrowsA=DD ⮇", "", "⮇"),
            ("xPairedArrowsB-UU ⇈", "", "⇈"),
            ("xPairedArrowsB=DD ⇊", "", "⇊"),
            ("xPairedArrowsB-LL ⇇", "", "⇇"),
            ("xPairedArrowsB-RR ⇉", "", "⇉"),
            ("xPairedArrowsC-LR ⇆", "", "⇆"),
            ("xPairedArrowsC-LR ⇄", "", "⇄"),
            ("xPairedArrowsC-UD ⇅", "", "⇅"),
            ("xPairedArrowsC-UD ⇵", "", "⇵"),
            ("xPairedArrowsD-LR ⮀", "", "⮀"),
            ("xPairedArrowsD-LR ⮂", "", "⮂"),
            ("xPairedArrowsD-UD ⮁", "", "⮁"),
            ("xPairedArrowsD-UD ⮃", "", "⮃"),
            ("xPairedArrowsE-LR ⭾", "", "⭾"),
            ("xPairedArrowsE-UD ⭿", "", "⭿"),

            ("xSharpTurnArrowsA-L ⮠",  "",  "⮠"),
            ("xSharpTurnArrowsA-R ⮡",  "",  "⮡"),
            ("xSharpTurnArrowsA-L ⮢",  "",  "⮢"),
            ("xSharpTurnArrowsA-R ⮣",  "",  "⮣"),
            ("xSharpTurnArrowsB-U ⮤",  "",  "⮤"),
            ("xSharpTurnArrowsB-D ⮦",  "",  "⮦"),
            ("xSharpTurnArrowsB-U ⮥",  "",  "⮥"),
            ("xSharpTurnArrowsB-D ⮧",  "",  "⮧"),
            ("xSharpTurnArrowsC-L ↰",  "",  "↰"),
            ("xSharpTurnArrowsC-R ↱",  "",  "↱"),
            ("xSharpTurnArrowsC-L ↲",  "",  "↲"),
            ("xSharpTurnArrowsC-R ↳",  "",  "↳"),
            ("xSharpTurnArrowsD-D ⬐",  "",  "⬐"),
            ("xSharpTurnArrowsD-U ⬑",  "",  "⬑"),
            ("xSharpTurnArrowsD-D ⬎",  "",  "⬎"),
            ("xSharpTurnArrowsD-U ⬏",  "",  "⬏"),
            ("xSharpTurnArrowsD-D ↴",  "",  "↴"),
            ("xSharpTurnArrowsD-L ↵",  "",  "↵"),
            ("xSharpTurnArrowsE-L ⮐",  "",  "⮐"),
            ("xSharpTurnArrowsE-R ⮑",  "",  "⮑"),
            ("xSharpTurnArrowsE-L ⮒",  "",  "⮒"),
            ("xSharpTurnArrowsE-R ⮓",  "",  "⮓"),

            ("xArrowsHookA-L ↩", "", "↩"),
            ("xArrowsHookA-R ↪", "", "↪"),
            ("xArrowsHookB-LR ⤣", "", "⤣"),
            ("xArrowsHookB-RU ⤤", "", "⤤"),
            ("xArrowsHookB-RD ⤥", "", "⤥"),
            ("xArrowsHookB-LD ⤦", "", "⤦"),
            ("xArrowsHookC-D ⭚", "", "⭚"),
            ("xArrowsHookC-RD ⭛", "", "⭛"),
            ("xArrowsHookD-L ↫", "", "↫"),
            ("xArrowsHookD-R ↬", "", "↬"),

            ( "xArrowDoubleA-L  ⇐",  " ", "⇐"),
            ( "xArrowDoubleA-R  ⇒",  " ", "⇒"),
            ( "xArrowDoubleA-U  ⇑",  " ", "⇑"),
            ( "xArrowDoubleA-D  ⇓",  " ", "⇓"),
            ( "xArrowDoubleA-LR ⇔",  " ", "⇔"),
            ( "xArrowDoubleA-UD ⇕",  " ", "⇕"),
            ( "xArrowDoubleA-LU ⇖",  " ", "⇖"),
            ( "xArrowDoubleA-RU ⇗",  " ", "⇗"),
            ( "xArrowDoubleA-RD ⇘",  " ", "⇘"),
            ( "xArrowDoubleA-LD ⇙",  " ", "⇙"),
            ( "xArrowDoubleA-L ⟸",  " ", "⟸"),
            ( "xArrowDoubleA-R ⟹",  " ", "⟹"),
            ( "xArrowDoubleA-LR ⟺",  " ", "⟺"),
            ( "xArrowDoubleB-L ⇍",  " ", "⇍"),
            ( "xArrowDoubleB-R ⇏",  " ", "⇏"),
            ( "xArrowDoubleB-LR ⇎",  " ", "⇎"),
            ( "xArrowDoubleB-L ⤂",  " ", "⤂"),
            ( "xArrowDoubleB-R ⤃",  " ", "⤃"),
            ( "xArrowDoubleB-LR ⤄",  " ", "⤄"),
            ( "xArrowDoubleB-L ⤆",  " ", "⤆"),
            ( "xArrowDoubleB-R ⤇",  " ", "⤇"),
            ( "xArrowTripleA-L ⬱",  " ", "⬱"),
            ( "xArrowTripleA-R ⇶",  " ", "⇶"),
            ( "xArrowTripleB-L ⇚",  " ", "⇚"),
            ( "xArrowTripleB-R ⇛",  " ", "⇛"),
            ( "xArrowTripleC-U ⤊",  " ", "⤊"),
            ( "xArrowTripleC-D ⤋",  " ", "⤋"),
            ( "xArrowQuadruple-L ⭅",  " ", "⭅"),
            ( "xArrowQuadruple-R ⭆",  " ", "⭆"),
            ( "xArrowQuadruple-U ⟰",  " ", "⟰"),
            ( "xArrowQuadruple-D ⟱",  " ", "⟱"),

            ("xsup0", "Sub/Subscript", "⁰" ),
            ("xsup1", "Sub/Subscript", "¹" ),
            ("xsup2", "Sub/Subscript", "²" ),
            ("xsup3", "Sub/Subscript", "³" ),
            ("xsup4", "Sub/Subscript", "⁴" ),
            ("xsup5", "Sub/Subscript", "⁵" ),
            ("xsup6", "Sub/Subscript", "⁶" ),
            ("xsup7", "Sub/Subscript", "⁷" ),
            ("xsup8", "Sub/Subscript", "⁸" ),
            ("xsup9", "Sub/Subscript", "⁹" ),
            ("xsup+", "Sub/Subscript", "⁺" ),
            ("xsup-", "Sub/Subscript", "⁻" ),
            ("xsup=", "Sub/Subscript", "⁼" ),
            ("xsup(", "Sub/Subscript", "⁽" ),
            ("xsup)", "Sub/Subscript", "⁾" ),
            ("xsub0", "Sub/Subscript", "₀" ),
            ("xsub1", "Sub/Subscript", "₁" ),
            ("xsub2", "Sub/Subscript", "₂" ),
            ("xsub3", "Sub/Subscript", "₃" ),
            ("xsub4", "Sub/Subscript", "₄" ),
            ("xsub5", "Sub/Subscript", "₅" ),
            ("xsub6", "Sub/Subscript", "₆" ),
            ("xsub7", "Sub/Subscript", "₇" ),
            ("xsub8", "Sub/Subscript", "₈" ),
            ("xsub9", "Sub/Subscript", "₉" ),
            ("xsub+", "Sub/Subscript", "₊" ),
            ("xsub-", "Sub/Subscript", "₋" ),
            ("xsub=", "Sub/Subscript", "₌" ),
            ("xsub(", "Sub/Subscript", "₍" ),
            ("xsub)", "Sub/Subscript", "₎" ),

            ("xMathOps-Sum ∑",  "Math Symbols", "∑" ),
            ("xMathOps-Sum ⨊", "Math Symbols", "⨊" ),
            ("xMathOps-Sum ⨁", "Math Symbols", "⨁" ),
            ("xMathOps-Product ⨀", "Math Symbols", "⨀" ),
            ("xMathOps-Product ⨂", "Math Symbols", "⨂" ),
            ("xMathOps-Product ∏", "Math Symbols", "∏" ),
            ("xMathOps-Product ∐", "Math Symbols", "∐" ),
            ("xMathOps-Product ⨉", "Math Symbols", "⨉" ),

            ( "xMathOps-Plus +",  "",  "+" ),
            ( "xMathOps-Plus ➕",  "",  "➕" ),
            ( "xMathOps-Plus ⨢",  "",  "⨢" ),
            ( "xMathOps-Plus ⨣",  "",  "⨣" ),
            ( "xMathOps-Plus ⨤",  "",  "⨤" ),
            ( "xMathOps-Plus ∔",  "",  "∔" ),
            ( "xMathOps-Plus ⨥",  "",  "⨥" ),
            ( "xMathOps-Plus ⨦",  "",  "⨦" ),
            ( "xMathOps-Plus ⨧",  "",  "⨧" ),
            ( "xMathOps-Plus ⨨",  "",  "⨨" ),
            ( "xMathOps-Plus ⨭",  "",  "⨭" ),
            ( "xMathOps-Plus ⨮",  "",  "⨮" ),
            ( "xMathOps-Plus ⧺",  "",  "⧺" ),
            ( "xMathOps-Plus ⧻",  "",  "⧻" ),
            ( "xMathOps-Plus ±",  "",  "±" ),
            ( "xMathOps-Plus ∓",  "",  "∓" ),

            ( "xMathOps-Minus −",  "",  "−" ),
            ( "xMathOps-Minus ∸",  "",  "∸" ),
            ( "xMathOps-Minus ⨪",  "",  "⨪" ),
            ( "xMathOps-Minus ⨩",  "",  "⨩" ),
            ( "xMathOps-Minus ⨫",  "",  "⨫" ),
            ( "xMathOps-Minus ⨬",  "",  "⨬" ),

            ( "xMathOps-Product ×",  "",  "×" ),
            ( "xMathOps-Product ✕",  "",  "✕" ),
            ( "xMathOps-Product ✖",  "",  "✖" ),
            ( "xMathOps-Product ⨰",  "",  "⨰" ),
            ( "xMathOps-Product ⨱",  "",  "⨱" ),
            ( "xMathOps-Product ⨲",  "",  "⨲" ),
            ( "xMathOps-Product ⨳",  "",  "⨳" ),
            ( "xMathOps-Product ⦻",  "",  "⦻" ),
            ( "xMathOps-Product ⨴",  "",  "⨴" ),
            ( "xMathOps-Product ⨵",  "",  "⨵" ),
            ( "xMathOps-Product ⨶",  "",  "⨶" ),
            ( "xMathOps-Product ⨷",  "",  "⨷" ),

            ( "xMathOps-Division ÷",  "",  "÷" ),
            ( "xMathOps-Division ∕",  "",  "∕" ),
            ( "xMathOps-Division ⋇",  "",  "⋇" ),
            ( "xMathOps-Division ⟌",  "",  "⟌" ),
            ( "xMathOps-Division ⟠",  "",  "⟠" ),

            ( "xMathOps-Circle-Plus ⊕",  "",  "⊕" ),
            ( "xMathOps-Circle-Minux ⊖",  "",  "⊖" ),
            ( "xMathOps-Circle-Minux ⊝",  "",  "⊝" ),

            ( "xMathOps-Circle-Times ⊗",  "",  "⊗" ),
            ( "xMathOps-Circle-Times ⊙",  "",  "⊙" ),
            ( "xMathOps-Circle-Times ⊚",  "",  "⊚" ),
            ( "xMathOps-Circle-Times ⊛",  "",  "⊛" ),
            ( "xMathOps-Circle-Times ⊜",  "",  "⊜" ),

            ( "xMathOps-Circle-Div ⊘",  "",  "⊘" ),
            ( "xMathOps-Circle-Div ⨸",  "",  "⨸" ),
            ( "xMathOps-Circle-Div ⦼",  "",  "⦼" ),
            ( "xMathOps-Circle-Div ⦵",  "",  "⦵" ),
            ( "xMathOps-Circle-Div ⦶",  "",  "⦶" ),
            ( "xMathOps-Circle-Div ⦷",  "",  "⦷" ),
            ( "xMathOps-Circle-Div ⦸",  "",  "⦸" ),
            ( "xMathOps-Circle-Div ⦹",  "",  "⦹" ),
            ( "xMathOps-Circle-Div ⦺",  "",  "⦺" ),
            ( "xMathOps-Circle-Div ⦽",  "",  "⦽" ),
            ( "xMathOps-Circle-Div ⧀",  "",  "⧀" ),
            ( "xMathOps-Circle-Div ⧁",  "",  "⧁" ),
            ( "xMathOps-Circle-Div ⧂",  "",  "⧂" ),
            ( "xMathOps-Circle-Div ⧃",  "",  "⧃" ),

            ( "xMathOps-Squared ⊞",  "",  "⊞" ),
            ( "xMathOps-Squared ⊟",  "",  "⊟" ),
            ( "xMathOps-Squared ⊠",  "",  "⊠" ),
            ( "xMathOps-Squared ⊡",  "",  "⊡" ),

            ( "xMathOps-Trangle ⨹",  "",  "⨹" ),
            ( "xMathOps-Trangle ⨺",  "",  "⨺" ),
            ( "xMathOps-Trangle ⨻",  "",  "⨻" ),
            ( "xMathOps-Trangle ⨞",  "",  "⨞" ),
            ( "xMathOps-Trangle ⧊",  "",  "⧊" ),
            ( "xMathOps-Trangle ⧋",  "",  "⧋" ),
            ( "xMathOps-Trangle ⧌",  "",  "⧌" ),
            ( "xMathOps-Trangle ⧍",  "",  "⧍" ),
            ( "xMathOps-Unknow ⋆",  "",  "⋆" ),
            ( "xMathOps-Unknow ∗",  "",  "∗" ),
            ( "xMathOps-Unknow ∘",  "",  "∘" ),
            ( "xMathOps-Unknow ∙",  "",  "∙" ),
            ( "xMathOps-Unknow ⋅",  "",  "⋅" ),

            ( "xMathOps-Bracket ⌈",  "",  "⌈" ),
            ( "xMathOps-Bracket ⌉",  "",  "⌉" ),
            ( "xMathOps-Bracket ⌊",  "",  "⌊" ),
            ( "xMathOps-Bracket ⌋",  "",  "⌋" ),
            ( "xMathOps-Bracket ⫍",  "",  "⫍" ),
            ( "xMathOps-Bracket ⫎",  "",  "⫎" ),

            ( "xMathOps-Integral-A ∫",  "",  "∫" ),
            ( "xMathOps-Integral-A ∬",  "",  "∬" ),
            ( "xMathOps-Integral-A ∭",  "",  "∭" ),
            ( "xMathOps-Integral-A ⨌",  "",  "⨌" ),
            ( "xMathOps-Integral-B ∮",  "",  "∮" ),
            ( "xMathOps-Integral-B ∯",  "",  "∯" ),
            ( "xMathOps-Integral-B ∰",  "",  "∰" ),
            ( "xMathOps-Integral-C ∱",  "",  "∱" ),
            ( "xMathOps-Integral-C ∲",  "",  "∲" ),
            ( "xMathOps-Integral-C ∳",  "",  "∳" ),
            ( "xMathOps-Integral-D ⨍",  "",  "⨍" ),
            ( "xMathOps-Integral-D ⨎",  "",  "⨎" ),
            ( "xMathOps-Integral-D ⨏",  "",  "⨏" ),
            ( "xMathOps-Integral-D ⨐",  "",  "⨐" ),
            ( "xMathOps-Integral-D ⨑",  "",  "⨑" ),
            ( "xMathOps-Integral-E ⨒",  "",  "⨒" ),
            ( "xMathOps-Integral-E ⨓",  "",  "⨓" ),
            ( "xMathOps-Integral-E ⨔",  "",  "⨔" ),
            ( "xMathOps-Integral-E ⨕",  "",  "⨕" ),
            ( "xMathOps-Integral-E ⨖",  "",  "⨖" ),
            ( "xMathOps-Integral-F ⨗",  "",  "⨗" ),
            ( "xMathOps-Integral-F ⨘",  "",  "⨘" ),
            ( "xMathOps-Integral-F ⨙",  "",  "⨙" ),
            ( "xMathOps-Integral-F ⨚",  "",  "⨚" ),
            ( "xMathOps-Integral-G ⨛",  "",  "⨛" ),
            ( "xMathOps-Integral-G ⨜",  "",  "⨜" ),
            ( "xMathOps-Integral-G ⨋",  "",  "⨋" ),

            ( "xMathOps-Derivative ∂",  "",  "∂" ),
            ( "xMathOps-Derivative ′",  "",  "′" ),
            ( "xMathOps-Derivative ″",  "",  "″" ),
            ( "xMathOps-Derivative ‴",  "",  "‴" ),
            ( "xMathOps-Derivative ∆",  "",  "∆" ),

            ( "xMathOps-linear-algera ⨯",  "",  "⨯" ),
            ( "xMathOps-linear-algera ∇",  "",  "∇" ),
            ( "xMathOps-linear-algera ⊹",  "",  "⊹" ),

            ( "xMathOps-Tilde ∼",  "",  "∼" ),
            ( "xMathOps-Tilde ∽",  "",  "∽" ),
            ( "xMathOps-Tilde ⩪",  "",  "⩪" ),
            ( "xMathOps-Tilde ⸟",  "",  "⸟" ),
            ( "xMathOps-Tilde ⩫",  "",  "⩫" ),
            ( "xMathOps-Tilde ⩳",  "",  "⩳" ),

            ( "xMathOps-Sinewave ∿",  "",  "∿" ),


            ( "xMathSetsA ∅",  "",  "∅"),
            ( "xMathSetsA ⦰",  "",  "⦰"),
            ( "xMathSetsA ⦱",  "",  "⦱"),
            ( "xMathSetsA ⦲",  "",  "⦲"),
            ( "xMathSetsA ⦳",  "",  "⦳"),
            ( "xMathSetsA ⦴",  "",  "⦴"),
            ( "xMathSetsB ℵ",  "",  "ℵ"),
            ( "xMathSetsB ∈",  "",  "∈"),
            ( "xMathSetsB ∋",  "",  "∋"),
            ( "xMathSetsB ∉",  "",  "∉"),
            ( "xMathSetsB ∌",  "",  "∌"),
            ( "xMathSetsB ⋶",  "",  "⋶"),
            ( "xMathSetsB ⋽",  "",  "⋽"),
            ( "xMathSetsB ⋲",  "",  "⋲"),
            ( "xMathSetsB ⋺",  "",  "⋺"),
            ( "xMathSetsB ⋳",  "",  "⋳"),
            ( "xMathSetsB ⋻",  "",  "⋻"),
            ( "xMathSetsC ∊",  "",  "∊"),
            ( "xMathSetsC ∍",  "",  "∍"),
            ( "xMathSetsC ⋷",  "",  "⋷"),
            ( "xMathSetsC ⋾",  "",  "⋾"),
            ( "xMathSetsC ⋴",  "",  "⋴"),
            ( "xMathSetsC ⋼",  "",  "⋼"),
            ( "xMathSetsC ⋵",  "",  "⋵"),
            ( "xMathSetsC ⋸",  "",  "⋸"),
            ( "xMathSetsC ⋹",  "",  "⋹"),
            ( "xMathSetsC ⫙",  "",  "⫙"),
            ( "xMathSetsC ⟒",  "",  "⟒"),

            ( "xMathSets-Union ∪", " ", "∪" ),
            ( "xMathSets-Union ⩁", " ", "⩁" ),
            ( "xMathSets-Union ⩂", " ", "⩂" ),
            ( "xMathSets-Union ⩅", " ", "⩅" ),
            ( "xMathSets-Union ⩌", " ", "⩌" ),
            ( "xMathSets-Union ⩏", " ", "⩏" ),
            ( "xMathSets-Union ⩐", " ", "⩐" ),

            ( "xMathSets-Inters ∩", " ", "∩" ),
            ( "xMathSets-Inters ⩀", " ", "⩀" ),
            ( "xMathSets-Inters ⩃", " ", "⩃" ),
            ( "xMathSets-Inters ⩄", " ", "⩄" ),
            ( "xMathSets-Inters ⩍", " ", "⩍" ),
            ( "xMathSets-Inters ⩎", " ", "⩎" ),

            ( "xMathSets-Binary ∖", " ", "∖" ),
            ( "xMathSets-Binary ⩆", " ", "⩆" ),
            ( "xMathSets-Binary ⩇", " ", "⩇" ),
            ( "xMathSets-Binary ⩈", " ", "⩈" ),
            ( "xMathSets-Binary ⩉", " ", "⩉" ),
            ( "xMathSets-Binary ⩊", " ", "⩊" ),
            ( "xMathSets-Binary ⩋", " ", "⩋" ),
            ( "xMathSets-Binary ⪽", " ", "⪽" ),
            ( "xMathSets-Binary ⪾", " ", "⪾" ),
            ( "xMathSets-Binary ⪿", " ", "⪿" ),
            ( "xMathSets-Binary ⫀", " ", "⫀" ),
            ( "xMathSets-Binary ⫁", " ", "⫁" ),
            ( "xMathSets-Binary ⫂", " ", "⫂" ),
            ( "xMathSets-Binary ⋒", " ", "⋒" ),
            ( "xMathSets-Binary ⋓", " ", "⋓" ),

            ( "xMathSets-N-nary ⋂", " ", "⋂" ),
            ( "xMathSets-N-nary ⋃", " ", "⋃" ),
            ( "xMathSets-N-nary ⊌", " ", "⊌" ),
            ( "xMathSets-N-nary ⊍", " ", "⊍" ),
            ( "xMathSets-N-nary ⊎", " ", "⊎" ),
            ( "xMathSets-N-nary ⨃", " ", "⨃" ),
            ( "xMathSets-N-nary ⨄", " ", "⨄" ),
            ( "xMathSets-N-nary ⨅", " ", "⨅" ),
            ( "xMathSets-N-nary ⨆", " ", "⨆" ),

            ( "xMathSets-Join ⨝", " ", "⨝" ),
            ( "xMathSets-Join ⟕", " ", "⟕" ),
            ( "xMathSets-Join ⟖", " ", "⟖" ),
            ( "xMathSets-Join ⟗", " ", "⟗" ),

            ( "xEmoji-money 💰", "", "💰" ), 
            ( "xEmoji-money 💱", "", "💱" ), 
            ( "xEmoji-money 💲", "", "💲" ), 
            ( "xEmoji-money 💳", "", "💳" ), 
            ( "xEmoji-money 💴", "", "💴" ), 
            ( "xEmoji-money 💵", "", "💵" ), 
            ( "xEmoji-money 💶", "", "💶" ), 
            ( "xEmoji-money 💷", "", "💷" ), 
            ( "xEmoji-money 💸", "", "💸" ), 
            ( "xEmoji-money 🧾", "", "🧾" ), 
            ( "xEmoji-money 💅", "", "💅" ), 
            ( "xEmoji-money 🛒", "", "🛒" ), 
            ( "xEmoji-money 🔮", "", "🔮" ), 
            ( "xEmoji-money 💎", "", "💎" ), 
            ( "xEmoji-money 💍", "", "💍" ), 
            ( "xEmoji-money 🎀", "", "🎀" ), 
            ( "xEmoji-money 🕯", "", "🕯" ), 
            ( "xEmoji-money 🔦", "", "🔦" ), 
            ( "xEmoji-money 🔔", "", "🔔" ), 
            ( "xEmoji-money 🕭", "", "🕭" ), 
            ( "xEmoji-money ⌚", "", "⌚" ), 
            ( "xEmoji-money ⌛", "", "⌛" ), 
            ( "xEmoji-money ⏳", "", "⏳" ),

            ( "xEmoji-key ⚿", "", "⚿" ), 
            ( "xEmoji-key 🗝", "", "🗝" ), 
            ( "xEmoji-key 🔑", "", "🔑" ), 
            ( "xEmoji-lock 🔏", "", "🔏" ), 
            ( "xEmoji-lock 🔐", "", "🔐" ), 
            ( "xEmoji-lock 🔒", "", "🔒" ), 
            ( "xEmoji-lock 🔓", "", "🔓" ), 
            ( "xEmoji- 🎨", "", "🎨" ),

            ( "xEmoji-medal 🎖", "", "🎖" ), 
            ( "xEmoji-ribbon 🎗", "", "🎗" ), 
            ( "xEmoji-sword 🔪", "", "🔪" ), 
            ( "xEmoji-sword 🗡", "", "🗡" ), 
            ( "xEmoji-sword ⚔", "", "⚔" ), 
            ( "xEmoji-watergun 🔫", "", "🔫" ), 
            ( "xEmoji-bomb 💣", "", "💣" ), 
            ( "xEmoji-bomb 🧨", "", "🧨" ),

            ( "xEmoji-Movie 🎬", "", "🎬" ), 
            ( "xEmoji-Movie 🎭", "", "🎭" ), 
            ( "xEmoji-Movie 🎫", "", "🎫" ), 
            ( "xEmoji-Movie 🎞", "", "🎞" ), 
            ( "xEmoji-Movie 🎟", "", "🎟" ),

            ( "xEmoji-bathroom 🚪", "", "🚪" ), 
            ( "xEmoji-bathroom 🚿", "", "🚿" ), 
            ( "xEmoji-bathroom 🛀", "", "🛀" ), 
            ( "xEmoji-bathroom 🛁", "", "🛁" ), 
            ( "xEmoji-bathroom 🚽", "", "🚽" ), 
            ( "xEmoji-bathroom 🧻", "", "🧻" ), 
            ( "xEmoji-bathroom 🧼", "", "🧼" ), 
            ( "xEmoji-bathroom 🧽", "", "🧽" ), 
            ( "xEmoji-bathroom 🧴", "", "🧴" ), 
            ( "xEmoji-bathroom 🪒", "", "🪒" ), 
            ( "xEmoji-bathroom 🧹", "", "🧹" ), 
            ( "xEmoji-bathroom 🧺", "", "🧺" ), 
            ( "xEmoji-bathroom 💺", "", "💺" ), 
            ( "xEmoji-bathroom 🧳", "", "🧳" ), 
            ( "xEmoji-bathroom 🗺", "", "🗺" ),

            ( "xEmoji-medical 💊", "", "💊" ), 
            ( "xEmoji-medical 🩸", "", "🩸" ), 
            ( "xEmoji-medical 💉", "", "💉" ), 
            ( "xEmoji-medical 🩹", "", "🩹" ), 
            ( "xEmoji-medical 🩺", "", "🩺" ),

            ( "xEmoji-science 🧮", "", "🧮" ), 
            ( "xEmoji-science 🔬", "", "🔬" ), 
            ( "xEmoji-science 🔭", "", "🔭" ), 
            ( "xEmoji-science 🧪", "", "🧪" ), 
            ( "xEmoji-science 🧫", "", "🧫" ), 
            ( "xEmoji-science ⚖", "", "⚖" ), 
            ( "xEmoji-science ⚗", "", "⚗" ), 
            ( "xEmoji-science 🧬", "", "🧬" ),

            ( "xEmoji-tools 🧰", "", "🧰" ), 
            ( "xEmoji-tools 🧲", "", "🧲" ), 
            ( "xEmoji-tools 🔩", "", "🔩" ), 
            ( "xEmoji-tools 🔧", "", "🔧" ), 
            ( "xEmoji-tools 🔨", "", "🔨" ), 
            ( "xEmoji-tools ⛏", "", "⛏" ), 
            ( "xEmoji-tools 🪓", "", "🪓" ), 
            ( "xEmoji-tools ⛓", "", "⛓" ), 
            ( "xEmoji-tools ⚙", "", "⚙" ), 
            ( "xEmoji-tools ⛭", "", "⛭" ), 
            ( "xEmoji-tools ⛮", "", "⛮" ), 
            ( "xEmoji-tools 🗜", "", "🗜" ), 
            ( "xEmoji-tools 🧱", "", "🧱" ),

            ( "xEmoji-teddy-doll 🧸", "", "🧸" ), 
            ( "xEmoji-teddy-doll 🎎", "", "🎎" ), 
            ( "xEmoji-teddy-doll 🕳", "", "🕳" ), 
            ( "xEmoji-teddy-doll 🎍", "", "🎍" ), 
            ( "xEmoji-teddy-doll 🏮", "", "🏮" ), 
            ( "xEmoji-teddy-doll 🎏", "", "🎏" ), 
            ( "xEmoji-teddy-doll 🎐", "", "🎐" ), 
            ( "xEmoji-teddy-doll 🪁", "", "🪁" ), 
            ( "xEmoji-teddy-doll ⚰", "", "⚰" ), 
            ( "xEmoji-teddy-doll ⚱", "", "⚱" ), 
            ( "xEmoji-teddy-doll 🏺", "", "🏺" ), 
            ( "xEmoji-teddy-doll ⚓", "", "⚓" ),

            ( "xEmoji-Religious 🕎", "", "🕎" ), 
            ( "xEmoji-Religious 📿", "", "📿" ), 
            ( "xEmoji-Religious 🧿", "", "🧿" ), 
            ( "xEmoji-Religious 🧧", "", "🧧" ), 
            ( "xEmoji-Religious 🧩", "", "🧩" ), 
            ( "xEmoji-Religious 🧯", "", "🧯" ), 
            ( "xEmoji-Religious 🧵", "", "🧵" ), 
            ( "xEmoji-Religious 🧶", "", "🧶" ), 
            ( "xEmoji-Religious 🧷", "", "🧷" ), 
            ( "xEmoji-Religious 🪑", "", "🪑" ), 
            ( "xEmoji-Religious 🪔", "", "🪔" ), 
            ( "xEmoji-Religious 🪕", "", "🪕" ), 
            ( "xEmoji-Religious 🪀", "", "🪀" ),

            ( "xEmoji-party 🎃", "", "🎃" ), 
            ( "xEmoji-party 🎁", "", "🎁" ), 
            ( "xEmoji-party 🎂", "", "🎂" ), 
            ( "xEmoji-party 🎈", "", "🎈" ), 
            ( "xEmoji-party 🎉", "", "🎉" ), 
            ( "xEmoji-party 🎊", "", "🎊" ),

            ( "xEmoji-breakfast 🧀", "", "🧀" ), 
            ( "xEmoji-breakfast 🥚", "", "🥚" ), 
            ( "xEmoji-breakfast 🍳", "", "🍳" ), 
            ( "xEmoji-breakfast 🥞", "", "🥞" ), 
            ( "xEmoji-breakfast 🧇", "", "🧇" ), 
            ( "xEmoji-breakfast 🧈", "", "🧈" ),

            ( "xEmoji-bread 🍞", "", "🍞" ), 
            ( "xEmoji-bread 🥐", "", "🥐" ), 
            ( "xEmoji-bread 🥯", "", "🥯" ), 
            ( "xEmoji-bread 🥖", "", "🥖" ), 
            ( "xEmoji-bread 🥨", "", "🥨" ), 
            ( "xEmoji-bread 🍔", "", "🍔" ), 
            ( "xEmoji-bread 🍟", "", "🍟" ), 
            ( "xEmoji-bread 🌭", "", "🌭" ), 
            ( "xEmoji-bread 🍕", "", "🍕" ), 
            ( "xEmoji-bread 🥪", "", "🥪" ), 
            ( "xEmoji-bread 🌮", "", "🌮" ), 
            ( "xEmoji-bread 🌯", "", "🌯" ), 
            ( "xEmoji-bread 🥙", "", "🥙" ), 
            ( "xEmoji-bread 🧆", "", "🧆" ), 
            ( "xEmoji-bread 🍝", "", "🍝" ), 
            ( "xEmoji-bread 🍛", "", "🍛" ), 
            ( "xEmoji-bread 🥘", "", "🥘" ), 
            ( "xEmoji-bread 🍲", "", "🍲" ), 
            ( "xEmoji-bread 🍤", "", "🍤" ), 
            ( "xEmoji-bread 🥗", "", "🥗" ), 
            ( "xEmoji-bread 🥫", "", "🥫" ),

            ( "xEmoji-Meat 🥓", "", "🥓" ), 
            ( "xEmoji-Meat 🍖", "", "🍖" ), 
            ( "xEmoji-Meat 🍗", "", "🍗" ), 
            ( "xEmoji-Meat 🥩", "", "🥩" ),

            ( "xEmoji-Chinese 🥢", "", "🥢" ), 
            ( "xEmoji-Chinese 🥡", "", "🥡" ), 
            ( "xEmoji-Chinese 🥟", "", "🥟" ), 
            ( "xEmoji-Chinese 🍚", "", "🍚" ), 
            ( "xEmoji-Chinese 🍜", "", "🍜" ), 
            ( "xEmoji-Chinese 🥠", "", "🥠" ), 
            ( "xEmoji-Chinese 🥮", "", "🥮" ),

            ( "xEmoji-Japaneses 🍘", "", "🍘" ), 
            ( "xEmoji-Japaneses 🍙", "", "🍙" ), 
            ( "xEmoji-Japaneses 🍣", "", "🍣" ), 
            ( "xEmoji-Japaneses 🍥", "", "🍥" ), 
            ( "xEmoji-Japaneses 🍱", "", "🍱" ), 
            ( "xEmoji-Japaneses 🍡", "", "🍡" ), 
            ( "xEmoji-Japaneses 🍢", "", "🍢" ),

            ( "xEmoji-Fruit 🍇", "", "🍇" ), 
            ( "xEmoji-Fruit 🍑", "", "🍑" ), 
            ( "xEmoji-Fruit 🍒", "", "🍒" ), 
            ( "xEmoji-Fruit 🍓", "", "🍓" ), 
            ( "xEmoji-Fruit 🥝", "", "🥝" ), 
            ( "xEmoji-Fruit 🍉", "", "🍉" ), 
            ( "xEmoji-Fruit 🍈", "", "🍈" ), 
            ( "xEmoji-Fruit 🍊", "", "🍊" ), 
            ( "xEmoji-Fruit 🍋", "", "🍋" ), 
            ( "xEmoji-Fruit 🍌", "", "🍌" ), 
            ( "xEmoji-Fruit 🍍", "", "🍍" ), 
            ( "xEmoji-Fruit 🥭", "", "🥭" ), 
            ( "xEmoji-Fruit 🥥", "", "🥥" ), 
            ( "xEmoji-Fruit 🍎", "", "🍎" ), 
            ( "xEmoji-Fruit 🍏", "", "🍏" ), 
            ( "xEmoji-Fruit 🍐", "", "🍐" ),

            ( "xEmoji-Veggie 🥬", "", "🥬" ), 
            ( "xEmoji-Veggie 🥦", "", "🥦" ), 
            ( "xEmoji-Veggie 🍄", "", "🍄" ), 
            ( "xEmoji-Veggie 🍅", "", "🍅" ), 
            ( "xEmoji-Veggie 🥕", "", "🥕" ), 
            ( "xEmoji-Veggie 🌶", "", "🌶" ), 
            ( "xEmoji-Veggie 🧄", "", "🧄" ), 
            ( "xEmoji-Veggie 🧅", "", "🧅" ), 
            ( "xEmoji-Veggie 🍆", "", "🍆" ), 
            ( "xEmoji-Veggie 🥒", "", "🥒" ), 
            ( "xEmoji-Veggie 🥑", "", "🥑" ), 
            ( "xEmoji-Veggie 🥔", "", "🥔" ), 
            ( "xEmoji-Veggie 🍠", "", "🍠" ), 
            ( "xEmoji-Veggie 🥜", "", "🥜" ),

            ( "xEmoji-cake 🍰", "", "🍰" ), 
            ( "xEmoji-cake 🎂", "", "🎂" ), 
            ( "xEmoji-cake 🧁", "", "🧁" ), 
            ( "xEmoji-cake 🥧", "", "🥧" ),

            ( "xEmoji-sweets 🍩", "", "🍩" ), 
            ( "xEmoji-sweets 🍪", "", "🍪" ), 
            ( "xEmoji-sweets 🍿", "", "🍿" ), 
            ( "xEmoji-sweets 🍮", "", "🍮" ), 
            ( "xEmoji-sweets 🍯", "", "🍯" ),

            ( "xEmoji-icecream 🍦", "", "🍦" ), 
            ( "xEmoji-icecream 🍨", "", "🍨" ), 
            ( "xEmoji-icecream 🍧", "", "🍧" ), 
            ( "xEmoji-icecream 🍫", "", "🍫" ), 
            ( "xEmoji-icecream 🍬", "", "🍬" ), 
            ( "xEmoji-icecream 🍭", "", "🍭" ),

            ( "xEmoji-beer 🍺", "", "🍺" ), 
            ( "xEmoji-beer 🍻", "", "🍻" ),
            ( "xEmoji-wine 🥂", "", "🥂" ), 
            ( "xEmoji-wine 🍷", "", "🍷" ), 
            ( "xEmoji-wine 🍸", "", "🍸" ), 
            ( "xEmoji-wine 🍹", "", "🍹" ), 
            ( "xEmoji-wine 🍶", "", "🍶" ), 
            ( "xEmoji-wine 🥃", "", "🥃" ), 
            ( "xEmoji-wine 🍾", "", "🍾" ),

            ( "xEmoji-coffee-milk-tea ☕", "", "☕" ), 
            ( "xEmoji-coffee-milk-tea 🍵", "", "🍵" ), 
            ( "xEmoji-coffee-milk-tea 🧉", "", "🧉" ), 
            ( "xEmoji-coffee-milk-tea 🥛", "", "🥛" ), 
            ( "xEmoji-coffee-milk-tea 🍼", "", "🍼" ), 
            ( "xEmoji-coffee-milk-tea 🥤", "", "🥤" ), 
            ( "xEmoji-coffee-milk-tea 🧃", "", "🧃" ), 
            ( "xEmoji-coffee-milk-tea 🧊", "", "🧊" ),

            ( "xEmoji-Utensils 🍴", "", "🍴" ), 
            ( "xEmoji-Utensils 🍽", "", "🍽" ), 
            ( "xEmoji-Utensils 🥣", "", "🥣" ), 
            ( "xEmoji-Utensils 🥄", "", "🥄" ), 
            ( "xEmoji-Utensils 🧂", "", "🧂" ), 

            ( "xClock-A ⏰",  " ",  "⏰" ),
            ( "xClock-A 🕰",  " ",  "🕰" ),
            ( "xClock-A ⌚",  " ",  "⌚" ),
            ( "xClock-A ⏱",  " ",  "⏱" ),
            ( "xClock-A ⏲",  " ",  "⏲" ),
            ( "xClock-hourglass ⌛",  " ",  "⌛" ),
            ( "xClock-hourglass ⏳",  " ",  "⏳" ),
            ( "xClock-hourglass ⧗",  " ",  "⧗" ),
            ( "xClock-hourglass ⧖",  " ",  "⧖" ),
            ( "xClock-hourglass 🝮",  " ",  "🝮" ),
            ( "xClock-hour-1 🕐",  " ",  "🕐" ),
            ( "xClock-hour-2 🕑",  " ",  "🕑" ),
            ( "xClock-hour-3 🕒",  " ",  "🕒" ),
            ( "xClock-hour-4 🕓",  " ",  "🕓" ),
            ( "xClock-hour-5 🕔",  " ",  "🕔" ),
            ( "xClock-hour-6 🕕",  " ",  "🕕" ),
            ( "xClock-hour-7 🕖",  " ",  "🕖" ),
            ( "xClock-hour-8 🕗",  " ",  "🕗" ),
            ( "xClock-hour-9 🕘",  " ",  "🕘" ),
            ( "xClock-hour-10 🕙",  " ",  "🕙" ),
            ( "xClock-hour-11 🕚",  " ",  "🕚" ),
            ( "xClock-hour-12 🕛",  " ",  "🕛" ),
            ( "xClock-half-1 🕜",  " ",  "🕜" ),
            ( "xClock-half-2 🕝",  " ",  "🕝" ),
            ( "xClock-half-3 🕞",  " ",  "🕞" ),
            ( "xClock-half-4 🕟",  " ",  "🕟" ),
            ( "xClock-half-5 🕠",  " ",  "🕠" ),
            ( "xClock-half-6 🕡",  " ",  "🕡" ),
            ( "xClock-half-7 🕢",  " ",  "🕢" ),
            ( "xClock-half-8 🕣",  " ",  "🕣" ),
            ( "xClock-half-9 🕤",  " ",  "🕤" ),
            ( "xClock-half-10 🕥",  " ",  "🕥" ),
            ( "xClock-half-11 🕦",  " ",  "🕦" ),
            ( "xClock-half-12 🕧",  " ",  "🕧" ),

            ( "xSex-male ♂",  " ", "♂" ), 
            ( "xSex-female ♀",  " ", "♀" ), 
            ( "xSex-neuter-eunuch ⚲",  " ", "⚲" ), 
            ( "xSex-heterosexual ⚤",  " ", "⚤" ), 
            ( "xSex-lesbian ⚢",  " ", "⚢" ), 
            ( "xSex-gay ⚣",  " ", "⚣" ), 
            ( "xSex-bisexual ⚥",  " ", "⚥" ), 
            ( "xSex-hermaphrodite ⚧",  " ", "⚧" ), 

            ( "xMusic-Emoji 🎹",  "", "🎹" ),
            ( "xMusic-Emoji 🎻",  "", "🎻" ),
            ( "xMusic-Emoji 🎷",  "", "🎷" ),
            ( "xMusic-Emoji 🎺",  "", "🎺" ),
            ( "xMusic-Emoji 🎸",  "", "🎸" ),
            ( "xMusic-Emoji 🥁",  "", "🥁" ),
            ( "xMusic-Emoji 🎵",  "", "🎵" ),
            ( "xMusic-Emoji 🎶",  "", "🎶" ),
            ( "xMusic-Emoji 🎼",  "", "🎼" ),
            ( "xMusic-Note 🎜",  "", "🎜" ),
            ( "xMusic-Note 🎝",  "", "🎝" ),
            ( "xMusic-Note ♩",  "", "♩" ),
            ( "xMusic-Note ♪",  "", "♪" ),
            ( "xMusic-Note ♫",  "", "♫" ),
            ( "xMusic-Note ♬",  "", "♬" ),
            ( "xMusic-Note 𝅜",  "", "𝅜" ),
            ( "xMusic-Note 𝅝",  "", "𝅝" ),
            ( "xMusic-Note 𝅗𝅥",  "", "𝅗𝅥" ),
            ( "xMusic-Note 𝅘𝅥",  "", "𝅘𝅥" ),
            ( "xMusic-Note 𝅘𝅥𝅮",  "", "𝅘𝅥𝅮" ),
            ( "xMusic-Note 𝅘𝅥𝅯",  "", "𝅘𝅥𝅯" ),
            ( "xMusic-Note 𝅘𝅥𝅰",  "", "𝅘𝅥𝅰" ),
            ( "xMusic-Note 𝅘𝅥𝅱",  "", "𝅘𝅥𝅱" ),
            ( "xMusic-Note 𝅘𝅥𝅲",  "", "𝅘𝅥𝅲" ),
            ( "xMusic-Reset 𝄺",  "", "𝄺" ),
            ( "xMusic-Reset 𝄩",  "", "𝄩" ),
            ( "xMusic-Reset 𝄻",  "", "𝄻" ),
            ( "xMusic-Reset 𝄼",  "", "𝄼" ),
            ( "xMusic-Reset 𝄽",  "", "𝄽" ),
            ( "xMusic-Reset 𝄾",  "", "𝄾" ),
            ( "xMusic-Reset 𝄿",  "", "𝄿" ),
            ( "xMusic-Reset 𝅀",  "", "𝅀" ),
            ( "xMusic-Reset 𝅁",  "", "𝅁" ),
            ( "xMusic-Reset 𝅂",  "", "𝅂" ),
            ( "xMusic-Reset 𝄒",  "", "𝄒" ),
            ( "xMusic-Misc 𝄓",  "", "𝄓" ),
            ( "xMusic-Misc 𝄐",  "", "𝄐" ),
            ( "xMusic-Misc 𝄑",  "", "𝄑" ),
            ( "xMusic-Misc 𝆏",  "", "𝆏" ),
            ( "xMusic-Misc 𝆐",  "", "𝆐" ),
            ( "xMusic-Misc 𝆑",  "", "𝆑" ),
            ( "xMusic-Misc 𝆒",  "", "𝆒" ),
            ( "xMusic-Misc 𝆓",  "", "𝆓" ),
            ( "xMusic-Misc 𝄀",  "", "𝄀" ),
            ( "xMusic-Misc 𝄁",  "", "𝄁" ),
            ( "xMusic-Misc 𝄂",  "", "𝄂" ),
            ( "xMusic-Misc 𝄃",  "", "𝄃" ),
            ( "xMusic-Misc 𝄄",  "", "𝄄" ),
            ( "xMusic-Misc 𝄅",  "", "𝄅" ),
            ( "xMusic-Misc 𝄔",  "", "𝄔" ),
            ( "xMusic-Misc 𝄕",  "", "𝄕" ),
            ( "xMusic-Misc 𝄆",  "", "𝄆" ),
            ( "xMusic-Misc 𝄇",  "", "𝄇" ),
            ( "xMusic-Misc 𝄈",  "", "𝄈" ),
            ( "xMusic-Misc 𝄉",  "", "𝄉" ),
            ( "xMusic-Misc 𝄊",  "", "𝄊" ),
            ( "xMusic-Misc 𝄋",  "", "𝄋" ),
            ( "xMusic-Misc 𝄌",  "", "𝄌" ),
            ( "xMusic-Misc 𝄍",  "", "𝄍" ),
            ( "xMusic-Misc 𝄎",  "", "𝄎" ),
            ( "xMusic-Misc 𝄏",  "", "𝄏" ),
            ( "xMusic-Staff 𝄖",  "", "𝄖" ),
            ( "xMusic-Staff 𝄗",  "", "𝄗" ),
            ( "xMusic-Staff 𝄘",  "", "𝄘" ),
            ( "xMusic-Staff 𝄙",  "", "𝄙" ),
            ( "xMusic-Staff 𝄛",  "", "𝄛" ),
            ( "xMusic-Staff 𝄚",  "", "𝄚" ),
            ( "xMusic-Staff 𝄚",  "", "𝄞𝄚" ),
            ( "xMusic-Staff 𝄚",  "", "𝄡𝄚" ),
            ( "xMusic-Staff 𝄚",  "", "𝄢𝄚" ),
            ( "xMusic-Staff 𝄚",  "", "𝄟𝄚" ),
            ( "xMusic-Staff 𝄚",  "", "𝄠𝄚" ),
            ( "xMusic-Staff 𝄚",  "", "𝄣𝄚" ),
            ( "xMusic-Staff 𝄚",  "", "𝄤𝄚" ),
            ( "xMusic-Staff 𝄚",  "", "𝄚𝄥" ),
            ( "xMusic-Key ♯",  "", "♯" ),
            ( "xMusic-Key 𝄪",  "", "𝄪" ),
            ( "xMusic-Key 𝄰",  "", "𝄰" ),
            ( "xMusic-Key 𝄱",  "", "𝄱" ),
            ( "xMusic-Key 𝄲",  "", "𝄲" ),
            ( "xMusic-Key ♭",  "", "♭" ),
            ( "xMusic-Key 𝄫",  "", "𝄫" ),
            ( "xMusic-Key 𝄬",  "", "𝄬" ),
            ( "xMusic-Key 𝄭",  "", "𝄭" ),
            ( "xMusic-Key 𝄳",  "", "𝄳" ),
            ( "xMusic-Key ♮",  "", "♮" ),
            ( "xMusic-Key 𝄮",  "", "𝄮" ),
            ( "xMusic-Key 𝄯",  "", "𝄯" ),
            ( "xMusic-Misc 𝄶",  "", "𝄶" ),
            ( "xMusic-Misc 𝄷",  "", "𝄷" ),
            ( "xMusic-Misc 𝄸",  "", "𝄸" ),
            ( "xMusic-Misc 𝄹",  "", "𝄹" ),
            ( "xMusic-Misc 𝄴",  "", "𝄴" ),
            ( "xMusic-Misc 𝄵",  "", "𝄵" ),
            ( "xMusic-Misc 𝆌",  "", "𝆌" ),
            ( "xMusic-Misc 𝆍",  "", "𝆍" ),
            ( "xMusic-Misc 𝆎",  "", "𝆎" ),
            ( "xMusic-Note 𝆔",  "", "𝆔" ),
            ( "xMusic-Note 𝆕",  "", "𝆕" ),
            ( "xMusic-Misc 𝆖",  "", "𝆖" ),
            ( "xMusic-Misc 𝆛",  "", "𝆛" ),
            ( "xMusic-Misc 𝆜",  "", "𝆜" ),
            ( "xMusic-Misc 𝆝",  "", "𝆝" ),
            ( "xMusic-Misc 𝆞",  "", "𝆞" ),
            ( "xMusic-Misc 𝆟",  "", "𝆟" ),
            ( "xMusic-Misc 𝆠",  "", "𝆠" ),
            ( "xMusic-Misc 𝆡",  "", "𝆡" ),
            ( "xMusic-Misc 𝆢",  "", "𝆢" ),
            ( "xMusic-Misc 𝆣",  "", "𝆣" ),
            ( "xMusic-Misc 𝆤",  "", "𝆤" ),
            ( "xMusic-Misc 𝆥",  "", "𝆥" ),
            ( "xMusic-Misc 𝆃",  "", "𝆃" ),
            ( "xMusic-Misc 𝆄",  "", "𝆄" ),
            ( "xMusic-Misc 𝆱",  "", "𝆱" ),
            ( "xMusic-Misc 𝆲",  "", "𝆲" ),
            ( "xMusic-Misc 𝆗",  "", "𝆗" ),
            ( "xMusic-Misc 𝆘",  "", "𝆘" ),
            ( "xMusic-Misc 𝆙",  "", "𝆙" ),
            ( "xMusic-Misc 𝆚",  "", "𝆚" ),
            ( "xMusic-Misc 𝆦",  "", "𝆦" ),
            ( "xMusic-Misc 𝆧",  "", "𝆧" ),
            ( "xMusic-Misc 𝆨",  "", "𝆨" ),
            ( "xMusic-Misc 𝆩",  "", "𝆩" ),
            ( "xMusic-Misc 𝆮",  "", "𝆮" ),
            ( "xMusic-Misc 𝆯",  "", "𝆯" ),
            ( "xMusic-Misc 𝆰",  "", "𝆰" ),
            ( "xMusic-Misc 𝄜",  "", "𝄜" ),
            ( "xMusic-Misc 𝄝",  "", "𝄝" ),
            ( "xMusic-Misc 𝆶",  "", "𝆶" ),
            ( "xMusic-Misc 𝆷",  "", "𝆷" ),
            ( "xMusic-Misc 𝆸",  "", "𝆸" ),
            ( "xMusic-Misc 𝆺",  "", "𝆺" ),
            ( "xMusic-Misc 𝆺𝅥",  "", "𝆺𝅥" ),
            ( "xMusic-Misc 𝆺𝅥𝅮",  "", "𝆺𝅥𝅮" ),
            ( "xMusic-Misc 𝆺𝅥𝅯",  "", "𝆺𝅥𝅯" ),
            ( "xMusic-Misc 𝆹",  "", "𝆹" ),
            ( "xMusic-Misc 𝆹𝅥",  "", "𝆹𝅥" ),
            ( "xMusic-Misc 𝆹𝅥𝅮",  "", "𝆹𝅥𝅮" ),
            ( "xMusic-Misc 𝆹𝅥𝅯",  "", "𝆹𝅥𝅯" ),
            ( "xMusic-Misc 𝇁",  "", "𝇁" ),
            ( "xMusic-Misc 𝇂",  "", "𝇂" ),
            ( "xMusic-Misc 𝇃",  "", "𝇃" ),
            ( "xMusic-Misc 𝇄",  "", "𝇄" ),
            ( "xMusic-Misc 𝇅",  "", "𝇅" ),
            ( "xMusic-Misc 𝇆",  "", "𝇆" ),
            ( "xMusic-Misc 𝇏",  "", "𝇏" ),
            ( "xMusic-Misc 𝇇",  "", "𝇇" ),
            ( "xMusic-Misc 𝇈",  "", "𝇈" ),
            ( "xMusic-Misc 𝇉",  "", "𝇉" ),
            ( "xMusic-Misc 𝇊",  "", "𝇊" ),
            ( "xMusic-Misc 𝇋",  "", "𝇋" ),
            ( "xMusic-Misc 𝇌",  "", "𝇌" ),
            ( "xMusic-Misc 𝇍",  "", "𝇍" ),
            ( "xMusic-Misc 𝇎",  "", "𝇎" ),
            ( "xMusic-Misc 𝇐",  "", "𝇐" ),
            ( "xMusic-Misc 𝇑",  "", "𝇑" ),
            ( "xMusic-Misc 𝇒",  "", "𝇒" ),
            ( "xMusic-Misc 𝇓",  "", "𝇓" ),
            ( "xMusic-Misc 𝇔",  "", "𝇔" ),
            ( "xMusic-Misc 𝇕",  "", "𝇕" ),
            ( "xMusic-Misc 𝇖",  "", "𝇖" ),
            ( "xMusic-Misc 𝇗",  "", "𝇗" ),
            ( "xMusic-Misc 𝇘",  "", "𝇘" ),
            ( "xMusic-Misc 𝇙",  "", "𝇙" ),
            ( "xMusic-Misc 𝇚",  "", "𝇚" ),
            ( "xMusic-Misc 𝇛",  "", "𝇛" ),
            ( "xMusic-Misc 𝇜",  "", "𝇜" ),
            ( "xMusic-Misc 𝇝",  "", "𝇝" ),
            ( "xMusic-Misc 𝆳",  "", "𝆳" ),
            ( "xMusic-Misc 𝆴",  "", "𝆴" ),
            ( "xMusic-Misc 𝆵",  "", "𝆵" ),
            ( "xMusic-Misc 𝅃",  "", "𝅃" ),
            ( "xMusic-Misc 𝅄",  "", "𝅄" ),
            ( "xMusic-Misc 𝅅",  "", "𝅅" ),
            ( "xMusic-Misc 𝅖",  "", "𝅖" ),
            ( "xMusic-Misc 𝅆",  "", "𝅆" ),
            ( "xMusic-Misc 𝅈",  "", "𝅈" ),
            ( "xMusic-Misc 𝅊",  "", "𝅊" ),
            ( "xMusic-Misc 𝅌",  "", "𝅌" ),
            ( "xMusic-Misc 𝅎",  "", "𝅎" ),
            ( "xMusic-Misc 𝅐",  "", "𝅐" ),
            ( "xMusic-Misc 𝅒",  "", "𝅒" ),
            ( "xMusic-Misc 𝅔",  "", "𝅔" ),
            ( "xMusic-Misc 𝅗",  "", "𝅗" ),
            ( "xMusic-Misc 𝅚",  "", "𝅚" ),
            ( "xMusic-Misc 𝅇",  "", "𝅇" ),
            ( "xMusic-Misc 𝅉",  "", "𝅉" ),
            ( "xMusic-Misc 𝅋",  "", "𝅋" ),
            ( "xMusic-Misc 𝅍",  "", "𝅍" ),
            ( "xMusic-Misc 𝅏",  "", "𝅏" ),
            ( "xMusic-Misc 𝅑",  "", "𝅑" ),
            ( "xMusic-Misc 𝅓",  "", "𝅓" ),
            ( "xMusic-Misc 𝅕",  "", "𝅕" ),
            ( "xMusic-Misc 𝅘",  "", "𝅘" ),
            ( "xMusic-Misc 𝅛",  "", "𝅛" ),
            ( "xMusic-Misc 𝅪",  "", "𝅪" ),
            ( "xMusic-Misc 𝅫",  "", "𝅫" ),
            ( "xMusic-Misc 𝅬",  "", "𝅬" ),


            ("xGreek-U-a Α", "", "Α"),
            ("xGreek-U-b Β", "", "Β"),
            ("xGreek-U-c Γ", "", "Γ"),
            ("xGreek-U-d Δ", "", "Δ"),
            ("xGreek-U-e Ε", "", "Ε"),
            ("xGreek-U-f Ζ", "", "Ζ"),
            ("xGreek-U-g Η", "", "Η"),
            ("xGreek-U-h Θ", "", "Θ"),
            ("xGreek-U-i Ι", "", "Ι"),
            ("xGreek-U-j Κ", "", "Κ"),
            ("xGreek-U-k Λ", "", "Λ"),
            ("xGreek-U-l Μ", "", "Μ"),
            ("xGreek-U-m Ν", "", "Ν"),
            ("xGreek-U-n Ξ", "", "Ξ"),
            ("xGreek-U-o Ο", "", "Ο"),
            ("xGreek-U-p Π", "", "Π"),
            ("xGreek-U-q Ρ", "", "Ρ"),
            ("xGreek-U-r Σ", "", "Σ"),
            ("xGreek-U-s Τ", "", "Τ"),
            ("xGreek-U-t Υ", "", "Υ"),
            ("xGreek-U-u Φ", "", "Φ"),
            ("xGreek-U-v Χ", "", "Χ"),
            ("xGreek-U-w Ψ", "", "Ψ"),
            ("xGreek-U-x Ω", "", "Ω"),

            ("xGreek-L-a α", "", "α"),
            ("xGreek-L-b β", "", "β"),
            ("xGreek-L-c γ", "", "γ"),
            ("xGreek-L-d δ", "", "δ"),
            ("xGreek-L-e ε", "", "ε"),
            ("xGreek-L-f ζ", "", "ζ"),
            ("xGreek-L-g η", "", "η"),
            ("xGreek-L-h θ", "", "θ"),
            ("xGreek-L-i ι", "", "ι"),
            ("xGreek-L-j κ", "", "κ"),
            ("xGreek-L-k λ", "", "λ"),
            ("xGreek-L-l μ", "", "μ"),
            ("xGreek-L-m ν", "", "ν"),
            ("xGreek-L-n ξ", "", "ξ"),
            ("xGreek-L-o ο", "", "ο"),
            ("xGreek-L-p π", "", "π"),
            ("xGreek-L-q ρ", "", "ρ"),
            ("xGreek-L-r σ", "", "σ"),
            ("xGreek-L-s τ", "", "τ"),
            ("xGreek-L-t υ", "", "υ"),
            ("xGreek-L-u φ", "", "φ"),
            ("xGreek-L-v χ", "", "χ"),
            ("xGreek-L-w ψ", "", "ψ"),
            ("xGreek-L-x ω", "", "ω"),

            ("xGreek-BU-a 𝚨", "", "𝚨"),
            ("xGreek-BU-b 𝚩", "", "𝚩"),
            ("xGreek-BU-c 𝚪", "", "𝚪"),
            ("xGreek-BU-d 𝚫", "", "𝚫"),
            ("xGreek-BU-e 𝚬", "", "𝚬"),
            ("xGreek-BU-f 𝚭", "", "𝚭"),
            ("xGreek-BU-g 𝚮", "", "𝚮"),
            ("xGreek-BU-h 𝚯", "", "𝚯"),
            ("xGreek-BU-i 𝚰", "", "𝚰"),
            ("xGreek-BU-j 𝚱", "", "𝚱"),
            ("xGreek-BU-k 𝚲", "", "𝚲"),
            ("xGreek-BU-l 𝚳", "", "𝚳"),
            ("xGreek-BU-m 𝚴", "", "𝚴"),
            ("xGreek-BU-n 𝚵", "", "𝚵"),
            ("xGreek-BU-o 𝚶", "", "𝚶"),
            ("xGreek-BU-p 𝚷", "", "𝚷"),
            ("xGreek-BU-q 𝚸", "", "𝚸"),
            ("xGreek-BU-r 𝚺", "", "𝚺"),
            ("xGreek-BU-s 𝚻", "", "𝚻"),
            ("xGreek-BU-t 𝚼", "", "𝚼"),
            ("xGreek-BU-u 𝚽", "", "𝚽"),
            ("xGreek-BU-v 𝚾", "", "𝚾"),
            ("xGreek-BU-w 𝚿", "", "𝚿"),
            ("xGreek-BU-x 𝛀", "", "𝛀"),

            ("xGreek-BL-a 𝛂", "", "𝛂"),
            ("xGreek-BL-b 𝛃", "", "𝛃"),
            ("xGreek-BL-c 𝛄", "", "𝛄"),
            ("xGreek-BL-d 𝛅", "", "𝛅"),
            ("xGreek-BL-e 𝛆", "", "𝛆"),
            ("xGreek-BL-f 𝛇", "", "𝛇"),
            ("xGreek-BL-g 𝛈", "", "𝛈"),
            ("xGreek-BL-h 𝛉", "", "𝛉"),
            ("xGreek-BL-i 𝛊", "", "𝛊"),
            ("xGreek-BL-j 𝛋", "", "𝛋"),
            ("xGreek-BL-k 𝛌", "", "𝛌"),
            ("xGreek-BL-l 𝛍", "", "𝛍"),
            ("xGreek-BL-m 𝛎", "", "𝛎"),
            ("xGreek-BL-n 𝛏", "", "𝛏"),
            ("xGreek-BL-o 𝛐", "", "𝛐"),
            ("xGreek-BL-p 𝛑", "", "𝛑"),
            ("xGreek-BL-q 𝛒", "", "𝛒"),
            ("xGreek-BL-r 𝛔", "", "𝛔"),
            ("xGreek-BL-s 𝛕", "", "𝛕"),
            ("xGreek-BL-t 𝛖", "", "𝛖"),
            ("xGreek-BL-u 𝛗", "", "𝛗"),
            ("xGreek-BL-v 𝛘", "", "𝛘"),
            ("xGreek-BL-w 𝛙", "", "𝛙"),
            ("xGreek-BL-x 𝛚", "", "𝛚"),

            ("xGreek-IU-a 𝛢", "", "𝛢"),
            ("xGreek-IU-b 𝛣", "", "𝛣"),
            ("xGreek-IU-c 𝛤", "", "𝛤"),
            ("xGreek-IU-d 𝛥", "", "𝛥"),
            ("xGreek-IU-e 𝛦", "", "𝛦"),
            ("xGreek-IU-f 𝛧", "", "𝛧"),
            ("xGreek-IU-g 𝛨", "", "𝛨"),
            ("xGreek-IU-h 𝛩", "", "𝛩"),
            ("xGreek-IU-i 𝛪", "", "𝛪"),
            ("xGreek-IU-j 𝛫", "", "𝛫"),
            ("xGreek-IU-k 𝛬", "", "𝛬"),
            ("xGreek-IU-l 𝛭", "", "𝛭"),
            ("xGreek-IU-m 𝛮", "", "𝛮"),
            ("xGreek-IU-n 𝛯", "", "𝛯"),
            ("xGreek-IU-o 𝛰", "", "𝛰"),
            ("xGreek-IU-p 𝛱", "", "𝛱"),
            ("xGreek-IU-q 𝛲", "", "𝛲"),
            ("xGreek-IU-r 𝛴", "", "𝛴"),
            ("xGreek-IU-s 𝛵", "", "𝛵"),
            ("xGreek-IU-t 𝛶", "", "𝛶"),
            ("xGreek-IU-u 𝛷", "", "𝛷"),
            ("xGreek-IU-v 𝛸", "", "𝛸"),
            ("xGreek-IU-w 𝛹", "", "𝛹"),
            ("xGreek-IU-x 𝛺", "", "𝛺"),

            ("xGreek-IL-a 𝛼", "", "𝛼"),
            ("xGreek-IL-b 𝛽", "", "𝛽"),
            ("xGreek-IL-c 𝛾", "", "𝛾"),
            ("xGreek-IL-d 𝛿", "", "𝛿"),
            ("xGreek-IL-e 𝜀", "", "𝜀"),
            ("xGreek-IL-f 𝜁", "", "𝜁"),
            ("xGreek-IL-g 𝜂", "", "𝜂"),
            ("xGreek-IL-h 𝜃", "", "𝜃"),
            ("xGreek-IL-i 𝜄", "", "𝜄"),
            ("xGreek-IL-j 𝜅", "", "𝜅"),
            ("xGreek-IL-k 𝜆", "", "𝜆"),
            ("xGreek-IL-l 𝜇", "", "𝜇"),
            ("xGreek-IL-m 𝜈", "", "𝜈"),
            ("xGreek-IL-n 𝜉", "", "𝜉"),
            ("xGreek-IL-o 𝜊", "", "𝜊"),
            ("xGreek-IL-p 𝜋", "", "𝜋"),
            ("xGreek-IL-q 𝜌", "", "𝜌"),
            ("xGreek-IL-r 𝜎", "", "𝜎"),
            ("xGreek-IL-s 𝜏", "", "𝜏"),
            ("xGreek-IL-t 𝜐", "", "𝜐"),
            ("xGreek-IL-u 𝜑", "", "𝜑"),
            ("xGreek-IL-v 𝜒", "", "𝜒"),
            ("xGreek-IL-w 𝜓", "", "𝜓"),
            ("xGreek-IL-x 𝜔", "", "𝜔"),

            ("xDoubleStruck-A 𝔸", "", "𝔸"),
            ("xDoubleStruck-B 𝔹", "", "𝔹"),
            ("xDoubleStruck-C ℂ", "", "ℂ"),
            ("xDoubleStruck-D 𝔻", "", "𝔻"),
            ("xDoubleStruck-E 𝔼", "", "𝔼"),
            ("xDoubleStruck-F 𝔽", "", "𝔽"),
            ("xDoubleStruck-G 𝔾", "", "𝔾"),
            ("xDoubleStruck-H ℍ", "", "ℍ"),
            ("xDoubleStruck-I 𝕀", "", "𝕀"),
            ("xDoubleStruck-J 𝕁", "", "𝕁"),
            ("xDoubleStruck-K 𝕂", "", "𝕂"),
            ("xDoubleStruck-L 𝕃", "", "𝕃"),
            ("xDoubleStruck-M 𝕄", "", "𝕄"),
            ("xDoubleStruck-N ℕ", "", "ℕ"),
            ("xDoubleStruck-O 𝕆", "", "𝕆"),
            ("xDoubleStruck-P ℙ", "", "ℙ"),
            ("xDoubleStruck-Q ℚ", "", "ℚ"),
            ("xDoubleStruck-R ℝ", "", "ℝ"),
            ("xDoubleStruck-S 𝕊", "", "𝕊"),
            ("xDoubleStruck-T 𝕋", "", "𝕋"),
            ("xDoubleStruck-U 𝕌", "", "𝕌"),
            ("xDoubleStruck-V 𝕍", "", "𝕍"),
            ("xDoubleStruck-W 𝕎", "", "𝕎"),
            ("xDoubleStruck-X 𝕏", "", "𝕏"),
            ("xDoubleStruck-Y 𝕐", "", "𝕐"),
            ("xDoubleStruck-Z ℤ", "", "ℤ"),

            ("xDoubleStruck-a 𝕒", "", "𝕒"),
            ("xDoubleStruck-b 𝕓", "", "𝕓"),
            ("xDoubleStruck-c 𝕔", "", "𝕔"),
            ("xDoubleStruck-d 𝕕", "", "𝕕"),
            ("xDoubleStruck-e 𝕖", "", "𝕖"),
            ("xDoubleStruck-f 𝕗", "", "𝕗"),
            ("xDoubleStruck-g 𝕘", "", "𝕘"),
            ("xDoubleStruck-h 𝕙", "", "𝕙"),
            ("xDoubleStruck-i 𝕚", "", "𝕚"),
            ("xDoubleStruck-j 𝕛", "", "𝕛"),
            ("xDoubleStruck-k 𝕜", "", "𝕜"),
            ("xDoubleStruck-l 𝕝", "", "𝕝"),
            ("xDoubleStruck-m 𝕞", "", "𝕞"),
            ("xDoubleStruck-n 𝕟", "", "𝕟"),
            ("xDoubleStruck-o 𝕠", "", "𝕠"),
            ("xDoubleStruck-p 𝕡", "", "𝕡"),
            ("xDoubleStruck-q 𝕢", "", "𝕢"),
            ("xDoubleStruck-r 𝕣", "", "𝕣"),
            ("xDoubleStruck-s 𝕤", "", "𝕤"),
            ("xDoubleStruck-t 𝕥", "", "𝕥"),
            ("xDoubleStruck-u 𝕦", "", "𝕦"),
            ("xDoubleStruck-v 𝕧", "", "𝕧"),
            ("xDoubleStruck-w 𝕨", "", "𝕨"),
            ("xDoubleStruck-x 𝕩", "", "𝕩"),
            ("xDoubleStruck-y 𝕪", "", "𝕪"),
            ("xDoubleStruck-z 𝕫", "", "𝕫"),

            ("xDoubleStruck-0 𝟘", "", "𝟘"),
            ("xDoubleStruck-1 𝟙", "", "𝟙"),
            ("xDoubleStruck-2 𝟚", "", "𝟚"),
            ("xDoubleStruck-3 𝟛", "", "𝟛"),
            ("xDoubleStruck-4 𝟜", "", "𝟜"),
            ("xDoubleStruck-5 𝟝", "", "𝟝"),
            ("xDoubleStruck-6 𝟞", "", "𝟞"),
            ("xDoubleStruck-7 𝟟", "", "𝟟"),
            ("xDoubleStruck-8 𝟠", "", "𝟠"),
            ("xDoubleStruck-9 𝟡", "", "𝟡"),

            ("xScript-IU-a 𝐴", "", "𝐴"),
            ("xScript-IU-b 𝐵", "", "𝐵"),
            ("xScript-IU-c 𝐶", "", "𝐶"),
            ("xScript-IU-d 𝐷", "", "𝐷"),
            ("xScript-IU-e 𝐸", "", "𝐸"),
            ("xScript-IU-f 𝐹", "", "𝐹"),
            ("xScript-IU-g 𝐺", "", "𝐺"),
            ("xScript-IU-h 𝐻", "", "𝐻"),
            ("xScript-IU-i 𝐼", "", "𝐼"),
            ("xScript-IU-j 𝐽", "", "𝐽"),
            ("xScript-IU-k 𝐾", "", "𝐾"),
            ("xScript-IU-l 𝐿", "", "𝐿"),
            ("xScript-IU-m 𝑀", "", "𝑀"),
            ("xScript-IU-n 𝑁", "", "𝑁"),
            ("xScript-IU-o 𝑂", "", "𝑂"),
            ("xScript-IU-p 𝑃", "", "𝑃"),
            ("xScript-IU-q 𝑄", "", "𝑄"),
            ("xScript-IU-r 𝑅", "", "𝑅"),
            ("xScript-IU-s 𝑆", "", "𝑆"),
            ("xScript-IU-t 𝑇", "", "𝑇"),
            ("xScript-IU-u 𝑈", "", "𝑈"),
            ("xScript-IU-v 𝑉", "", "𝑉"),
            ("xScript-IU-w 𝑊", "", "𝑊"),
            ("xScript-IU-x 𝑋", "", "𝑋"),
            ("xScript-IU-y 𝑌", "", "𝑌"),
            ("xScript-IU-z 𝑍", "", "𝑍"),

            ("xScript-IL-a 𝑎", "", "𝑎"),
            ("xScript-IL-b 𝑏", "", "𝑏"),
            ("xScript-IL-c 𝑐", "", "𝑐"),
            ("xScript-IL-d 𝑑", "", "𝑑"),
            ("xScript-IL-e 𝑒", "", "𝑒"),
            ("xScript-IL-f 𝑓", "", "𝑓"),
            ("xScript-IL-g 𝑔", "", "𝑔"),
            ("xScript-IL-h ℎ", "", "ℎ"),
            ("xScript-IL-i 𝑖", "", "𝑖"),
            ("xScript-IL-j 𝑗", "", "𝑗"),
            ("xScript-IL-k 𝑘", "", "𝑘"),
            ("xScript-IL-l 𝑙", "", "𝑙"),
            ("xScript-IL-m 𝑚", "", "𝑚"),
            ("xScript-IL-n 𝑛", "", "𝑛"),
            ("xScript-IL-o 𝑜", "", "𝑜"),
            ("xScript-IL-p 𝑝", "", "𝑝"),
            ("xScript-IL-q 𝑞", "", "𝑞"),
            ("xScript-IL-r 𝑟", "", "𝑟"),
            ("xScript-IL-s 𝑠", "", "𝑠"),
            ("xScript-IL-t 𝑡", "", "𝑡"),
            ("xScript-IL-u 𝑢", "", "𝑢"),
            ("xScript-IL-v 𝑣", "", "𝑣"),
            ("xScript-IL-w 𝑤", "", "𝑤"),
            ("xScript-IL-x 𝑥", "", "𝑥"),
            ("xScript-IL-y 𝑦", "", "𝑦"),
            ("xScript-IL-z 𝑧", "", "𝑧"),

            ("xScript-BIU-a 𝑨", "", "𝑨"),
            ("xScript-BIU-b 𝑩", "", "𝑩"),
            ("xScript-BIU-c 𝑪", "", "𝑪"),
            ("xScript-BIU-d 𝑫", "", "𝑫"),
            ("xScript-BIU-e 𝑬", "", "𝑬"),
            ("xScript-BIU-f 𝑭", "", "𝑭"),
            ("xScript-BIU-g 𝑮", "", "𝑮"),
            ("xScript-BIU-h 𝑯", "", "𝑯"),
            ("xScript-BIU-i 𝑰", "", "𝑰"),
            ("xScript-BIU-j 𝑱", "", "𝑱"),
            ("xScript-BIU-k 𝑲", "", "𝑲"),
            ("xScript-BIU-l 𝑳", "", "𝑳"),
            ("xScript-BIU-m 𝑴", "", "𝑴"),
            ("xScript-BIU-n 𝑵", "", "𝑵"),
            ("xScript-BIU-o 𝑶", "", "𝑶"),
            ("xScript-BIU-p 𝑷", "", "𝑷"),
            ("xScript-BIU-q 𝑸", "", "𝑸"),
            ("xScript-BIU-r 𝑹", "", "𝑹"),
            ("xScript-BIU-s 𝑺", "", "𝑺"),
            ("xScript-BIU-t 𝑻", "", "𝑻"),
            ("xScript-BIU-u 𝑼", "", "𝑼"),
            ("xScript-BIU-v 𝑽", "", "𝑽"),
            ("xScript-BIU-w 𝑾", "", "𝑾"),
            ("xScript-BIU-x 𝑿", "", "𝑿"),
            ("xScript-BIU-y 𝒀", "", "𝒀"),
            ("xScript-BIU-z 𝒁", "", "𝒁"),

            ("xScript-BIL-a 𝒂", "", "𝒂"),
            ("xScript-BIL-b 𝒃", "", "𝒃"),
            ("xScript-BIL-c 𝒄", "", "𝒄"),
            ("xScript-BIL-d 𝒅", "", "𝒅"),
            ("xScript-BIL-e 𝒆", "", "𝒆"),
            ("xScript-BIL-f 𝒇", "", "𝒇"),
            ("xScript-BIL-g 𝒈", "", "𝒈"),
            ("xScript-BIL-h 𝒉", "", "𝒉"),
            ("xScript-BIL-i 𝒊", "", "𝒊"),
            ("xScript-BIL-j 𝒋", "", "𝒋"),
            ("xScript-BIL-k 𝒌", "", "𝒌"),
            ("xScript-BIL-l 𝒍", "", "𝒍"),
            ("xScript-BIL-m 𝒎", "", "𝒎"),
            ("xScript-BIL-n 𝒏", "", "𝒏"),
            ("xScript-BIL-o 𝒐", "", "𝒐"),
            ("xScript-BIL-p 𝒑", "", "𝒑"),
            ("xScript-BIL-q 𝒒", "", "𝒒"),
            ("xScript-BIL-r 𝒓", "", "𝒓"),
            ("xScript-BIL-s 𝒔", "", "𝒔"),
            ("xScript-BIL-t 𝒕", "", "𝒕"),
            ("xScript-BIL-u 𝒖", "", "𝒖"),
            ("xScript-BIL-v 𝒗", "", "𝒗"),
            ("xScript-BIL-w 𝒘", "", "𝒘"),
            ("xScript-BIL-x 𝒙", "", "𝒙"),
            ("xScript-BIL-y 𝒚", "", "𝒚"),
            ("xScript-BIL-z 𝒛", "", "𝒛"),

            ("xScript-NU-a 𝒜", "", "𝒜"),
            ("xScript-NU-b ℬ", "", "ℬ"),
            ("xScript-NU-c 𝒞", "", "𝒞"),
            ("xScript-NU-d 𝒟", "", "𝒟"),
            ("xScript-NU-e ℰ", "", "ℰ"),
            ("xScript-NU-f ℱ", "", "ℱ"),
            ("xScript-NU-g 𝒢", "", "𝒢"),
            ("xScript-NU-h ℋ", "", "ℋ"),
            ("xScript-NU-i ℐ", "", "ℐ"),
            ("xScript-NU-j 𝒥", "", "𝒥"),
            ("xScript-NU-k 𝒦", "", "𝒦"),
            ("xScript-NU-l ℒ", "", "ℒ"),
            ("xScript-NU-m ℳ", "", "ℳ"),
            ("xScript-NU-n 𝒩", "", "𝒩"),
            ("xScript-NU-o 𝒪", "", "𝒪"),
            ("xScript-NU-p 𝒫", "", "𝒫"),
            ("xScript-NU-q 𝒬", "", "𝒬"),
            ("xScript-NU-r ℛ", "", "ℛ"),
            ("xScript-NU-s 𝒮", "", "𝒮"),
            ("xScript-NU-t 𝒯", "", "𝒯"),
            ("xScript-NU-u 𝒰", "", "𝒰"),
            ("xScript-NU-v 𝒱", "", "𝒱"),
            ("xScript-NU-w 𝒲", "", "𝒲"),
            ("xScript-NU-x 𝒳", "", "𝒳"),
            ("xScript-NU-y 𝒴", "", "𝒴"),
            ("xScript-NU-z 𝒵", "", "𝒵"),

            ("xScript-NL-a 𝒶", "", "𝒶"),
            ("xScript-NL-b 𝒷", "", "𝒷"),
            ("xScript-NL-c 𝒸", "", "𝒸"),
            ("xScript-NL-d 𝒹", "", "𝒹"),
            ("xScript-NL-e ℯ", "", "ℯ"),
            ("xScript-NL-f 𝒻", "", "𝒻"),
            ("xScript-NL-g ℊ", "", "ℊ"),
            ("xScript-NL-h 𝒽", "", "𝒽"),
            ("xScript-NL-i 𝒾", "", "𝒾"),
            ("xScript-NL-j 𝒿", "", "𝒿"),
            ("xScript-NL-k 𝓀", "", "𝓀"),
            ("xScript-NL-l 𝓁", "", "𝓁"),
            ("xScript-NL-m 𝓂", "", "𝓂"),
            ("xScript-NL-n 𝓃", "", "𝓃"),
            ("xScript-NL-o ℴ", "", "ℴ"),
            ("xScript-NL-p 𝓅", "", "𝓅"),
            ("xScript-NL-q 𝓆", "", "𝓆"),
            ("xScript-NL-r 𝓇", "", "𝓇"),
            ("xScript-NL-s 𝓈", "", "𝓈"),
            ("xScript-NL-t 𝓉", "", "𝓉"),
            ("xScript-NL-u 𝓊", "", "𝓊"),
            ("xScript-NL-v 𝓋", "", "𝓋"),
            ("xScript-NL-w 𝓌", "", "𝓌"),
            ("xScript-NL-x 𝓍", "", "𝓍"),
            ("xScript-NL-y 𝓎", "", "𝓎"),
            ("xScript-NL-z 𝓏", "", "𝓏"),

            ("xScript-BU-a 𝓐", "", "𝓐"),
            ("xScript-BU-b 𝓑", "", "𝓑"),
            ("xScript-BU-c 𝓒", "", "𝓒"),
            ("xScript-BU-d 𝓓", "", "𝓓"),
            ("xScript-BU-e 𝓔", "", "𝓔"),
            ("xScript-BU-f 𝓕", "", "𝓕"),
            ("xScript-BU-g 𝓖", "", "𝓖"),
            ("xScript-BU-h 𝓗", "", "𝓗"),
            ("xScript-BU-i 𝓘", "", "𝓘"),
            ("xScript-BU-j 𝓙", "", "𝓙"),
            ("xScript-BU-k 𝓚", "", "𝓚"),
            ("xScript-BU-l 𝓛", "", "𝓛"),
            ("xScript-BU-m 𝓜", "", "𝓜"),
            ("xScript-BU-n 𝓝", "", "𝓝"),
            ("xScript-BU-o 𝓞", "", "𝓞"),
            ("xScript-BU-p 𝓟", "", "𝓟"),
            ("xScript-BU-q 𝓠", "", "𝓠"),
            ("xScript-BU-r 𝓡", "", "𝓡"),
            ("xScript-BU-s 𝓢", "", "𝓢"),
            ("xScript-BU-t 𝓣", "", "𝓣"),
            ("xScript-BU-u 𝓤", "", "𝓤"),
            ("xScript-BU-v 𝓥", "", "𝓥"),
            ("xScript-BU-w 𝓦", "", "𝓦"),
            ("xScript-BU-x 𝓧", "", "𝓧"),
            ("xScript-BU-y 𝓨", "", "𝓨"),
            ("xScript-BU-z 𝓩", "", "𝓩"),

            ("xScript-BL-a 𝓪", "", "𝓪"),
            ("xScript-BL-b 𝓫", "", "𝓫"),
            ("xScript-BL-c 𝓬", "", "𝓬"),
            ("xScript-BL-d 𝓭", "", "𝓭"),
            ("xScript-BL-e 𝓮", "", "𝓮"),
            ("xScript-BL-f 𝓯", "", "𝓯"),
            ("xScript-BL-g 𝓰", "", "𝓰"),
            ("xScript-BL-h 𝓱", "", "𝓱"),
            ("xScript-BL-i 𝓲", "", "𝓲"),
            ("xScript-BL-j 𝓳", "", "𝓳"),
            ("xScript-BL-k 𝓴", "", "𝓴"),
            ("xScript-BL-l 𝓵", "", "𝓵"),
            ("xScript-BL-m 𝓶", "", "𝓶"),
            ("xScript-BL-n 𝓷", "", "𝓷"),
            ("xScript-BL-o 𝓸", "", "𝓸"),
            ("xScript-BL-p 𝓹", "", "𝓹"),
            ("xScript-BL-q 𝓺", "", "𝓺"),
            ("xScript-BL-r 𝓻", "", "𝓻"),
            ("xScript-BL-s 𝓼", "", "𝓼"),
            ("xScript-BL-t 𝓽", "", "𝓽"),
            ("xScript-BL-u 𝓾", "", "𝓾"),
            ("xScript-BL-v 𝓿", "", "𝓿"),
            ("xScript-BL-w 𝔀", "", "𝔀"),
            ("xScript-BL-x 𝔁", "", "𝔁"),
            ("xScript-BL-y 𝔂", "", "𝔂"),
            ("xScript-BL-z 𝔃", "", "𝔃"),
            ]

    # def on_query_context(self, view, key, op, opr, match_all):
    #   print("VLL: on_query_context [%s] [%s] [%s] [%s] [%s]" % (view, key, op, opr, match_all))       

    # def on_selection_modified(self, view):
    #   print("VLL: on_selection_modified [%s]" % view)

    # def on_text_command(self, view, act, extras):
    #   act in ['move','drag_select','left_delete','right_delete','redo_or_repeat','find_next'] #....
    #   print("VLL: on_text_command [%s] [act %s] %s" % (view, act, extras))

    # def on_window_command(self, view, act, b):
    #   act in ['new_file', 'close']
    #   print("VLL: on_window_command [%s] [act %s] [%s]" % (view, act, b))

